# Makefile.in generated automatically by automake 1.4-p6 from Makefile.am

# Copyright (C) 1994, 1995-8, 1999, 2001 Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.


SHELL = /bin/sh

srcdir = .
top_srcdir = ..

prefix = /usr/local
exec_prefix = ${prefix}

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include

DESTDIR =

pkgdatadir = $(datadir)/glib
pkglibdir = $(libdir)/glib
pkgincludedir = $(includedir)/glib

top_builddir = ..

ACLOCAL = /home/general/cn_proc/glib-2.0.7/missing aclocal-1.4
AUTOCONF = /home/general/cn_proc/glib-2.0.7/missing autoconf
AUTOMAKE = /home/general/cn_proc/glib-2.0.7/missing automake-1.4
AUTOHEADER = /home/general/cn_proc/glib-2.0.7/missing autoheader

INSTALL = /usr/bin/install -c
INSTALL_PROGRAM = ${INSTALL} $(AM_INSTALL_PROGRAM_FLAGS)
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL}
transform = s,x,x,

NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
host_alias = 
host_triplet = x86_64-unknown-linux-gnu
AS = @AS@
AWK = gawk
CATALOGS =  ar.gmo az.gmo be.gmo bg.gmo ca.gmo cs.gmo de.gmo el.gmo es.gmo eu.gmo fr.gmo gl.gmo ja.gmo ko.gmo ms.gmo nl.gmo nn.gmo no.gmo pl.gmo pt.gmo pt_BR.gmo ro.gmo ru.gmo sk.gmo sl.gmo sv.gmo ta.gmo tr.gmo uk.gmo vi.gmo zh_CN.gmo zh_TW.gmo
CATOBJEXT = .gmo
CC = gcc
CXX = 
DATADIRNAME = share
DB2HTML = false
DISABLE_MEM_POOLS = 
DLLTOOL = @DLLTOOL@
ECHO = echo
ENABLE_GC_FRIENDLY = 
EXEEXT = 
GETTEXT_PACKAGE = glib20
GIO = giounix.lo
GLIBC21 = yes
GLIB_BINARY_AGE = 7
GLIB_DEBUG_FLAGS = 
GLIB_DEF = 
GLIB_GENMARSHAL = 
GLIB_INTERFACE_AGE = 7
GLIB_MAJOR_VERSION = 2
GLIB_MICRO_VERSION = 7
GLIB_MINOR_VERSION = 0
GLIB_VERSION = 2.0.7
GMODULE_DEF = 
GMOFILES =  ar.gmo az.gmo be.gmo bg.gmo ca.gmo cs.gmo de.gmo el.gmo es.gmo eu.gmo fr.gmo gl.gmo ja.gmo ko.gmo ms.gmo nl.gmo nn.gmo no.gmo pl.gmo pt.gmo pt_BR.gmo ro.gmo ru.gmo sk.gmo sl.gmo sv.gmo ta.gmo tr.gmo uk.gmo vi.gmo zh_CN.gmo zh_TW.gmo
GMSGFMT = /usr/bin/msgfmt
GOBJECT_DEF = 
GSPAWN = gspawn.lo
GTHREAD_COMPILE_IMPL_DEFINES = -D_POSIX4_DRAFT_SOURCE -D_POSIX4A_DRAFT10_SOURCE -U_OSF_SOURCE
GTHREAD_DEF = 
GTKDOC = false
G_LIBS_EXTRA = 
G_LIB_WIN32_RESOURCE = 
G_MODULE_BROKEN_RTLD_GLOBAL = 0
G_MODULE_HAVE_DLERROR = 1
G_MODULE_IMPL = G_MODULE_IMPL_DL
G_MODULE_LDFLAGS = -Wl,--export-dynamic
G_MODULE_LIBS = -ldl
G_MODULE_LIBS_EXTRA = 
G_MODULE_NEED_USCORE = 0
G_MODULE_PLUGIN_LIBS = 
G_MODULE_SUPPORTED = true
G_MODULE_WIN32_RESOURCE = 
G_OBJECT_WIN32_RESOURCE = 
G_THREAD_CFLAGS = -D_REENTRANT
G_THREAD_LIBS = -lpthread 
G_THREAD_LIBS_EXTRA = 
G_THREAD_WIN32_RESOURCE = 
HAVE_GTK_DOC = 
HTML_DIR = ${datadir}/gtk-doc/html
ICONV_LIBS = 
INDENT = 
INSTOBJEXT = .mo
INTLDEPS = 
INTLLIBS = 
INTLOBJS = 
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LN_S = ln -s
LT_AGE = 0
LT_CURRENT = 0
LT_CURRENT_MINUS_AGE = 0
LT_RELEASE = 2.0
LT_REVISION = 7
MAINT = #
MAKEINFO = /home/general/cn_proc/glib-2.0.7/missing makeinfo
MKINSTALLDIRS = ./mkinstalldirs
OBJDUMP = @OBJDUMP@
OBJEXT = o
PACKAGE = glib
PERL = perl
PERL_PATH = /usr/bin/perl
PKG_CONFIG = /usr/bin/pkg-config
PLATFORMDEP = 
POFILES =  ar.po az.po be.po bg.po ca.po cs.po de.po el.po es.po eu.po fr.po gl.po ja.po ko.po ms.po nl.po nn.po no.po pl.po pt.po pt_BR.po ro.po ru.po sk.po sl.po sv.po ta.po tr.po uk.po vi.po zh_CN.po zh_TW.po
POSUB = po
RANLIB = ranlib
REBUILD = 
STRIP = strip
STRIP_BEGIN = $(strip $(STRIP_DUMMY)
STRIP_DUMMY = 
STRIP_END = )
TESTGMODULE_EXP = 
USE_NLS = yes
VERSION = 2.0.7
ms_librarian = 

INCLUDES = -I$(top_srcdir) -I$(top_srcdir)/glib -I$(top_srcdir)/gmodule 

EFENCE = 

libglib = $(top_builddir)/glib/libglib-2.0.la
libgthread = $(top_builddir)/gthread/libgthread-2.0.la
libgmodule = $(top_builddir)/gmodule/libgmodule-2.0.la
libgobject = $(top_builddir)/gobject/libgobject-2.0.la

#libadd_libgmodule = #$(libgmodule)
#libadd_libglib = #$(libglib)
#no_undefined = #-no-undefined

#module_test_exp = #module-test.exp

EXTRA_DIST = \
	$(test_scripts)				\
	makefile.msc.in				\
	makefile.mingw.in			\
	casefold.txt				\
	casemap.txt				\
	gen-casefold-txt.pl			\
	gen-casemap-txt.pl			\
	iochannel-test-infile			\
	utf8.txt


BUILT_EXTRA_DIST = \
	makefile.mingw				\
	makefile.msc

#CXX_TEST = #cxx-test
CXX_TEST = 
#cxx_test_LDADD = #$(progs_ldadd)
#cxx_test_SOURCES = #cxx-test.C

timeloop = timeloop timeloop-closure
noinst_PROGRAMS = testglib patterntest testgdate testgdateparser unicode-normalize unicode-collate $(timeloop)
testglib_LDADD = $(libglib)
patterntest_LDADD = $(libglib)
testgdate_LDADD = $(libglib)
testgdateparser_LDADD = $(libglib)
unicode_normalize_LDADD = $(libglib)
unicode_collate_LDADD = $(libglib)
timeloop_LDADD = $(libglib)
timeloop_closure_LDADD = $(libglib) $(libgobject)

test_programs = \
	array-test				\
	$(CXX_TEST)				\
	date-test				\
	dirname-test				\
	gio-test				\
	hash-test				\
	iochannel-test				\
	list-test				\
	mainloop-test				\
	module-test				\
	node-test				\
	queue-test				\
	qsort-test				\
	rand-test				\
	relation-test				\
	shell-test				\
	slist-test				\
	spawn-test				\
	strfunc-test				\
	string-test				\
	strtod-test				\
	thread-test				\
	threadpool-test				\
	tree-test				\
	type-test				\
	unicode-caseconv			\
	unicode-encoding			\
	uri-test


test_scripts = run-markup-tests.sh

test_script_support_programs = markup-test

check_PROGRAMS = $(test_programs) $(test_script_support_programs)

TESTS = $(test_programs) $(test_scripts)
TESTS_ENVIRONMENT = srcdir=$(srcdir) \
	LIBCHARSET_ALIAS_DIR=$(top_builddir)/glib/libcharset


progs_ldadd = $(EFENCE) $(libglib) $(EFENCE)
thread_ldadd = $(libgthread) -lpthread  $(progs_ldadd)
module_ldadd = $(libgmodule) -ldl $(progs_ldadd)

array_test_LDADD = $(progs_ldadd)
date_test_LDADD = $(progs_ldadd)
dirname_test_LDADD = $(progs_ldadd)
gio_test_LDADD = $(progs_ldadd)
hash_test_LDADD = $(progs_ldadd)
iochannel_test_LDADD = $(progs_ldadd)
list_test_LDADD = $(progs_ldadd)
mainloop_test_LDADD = $(thread_ldadd)
markup_test_LDADD = $(progs_ldadd)
module_test_LDADD = $(module_ldadd) $(module_test_exp)
module_test_LDFLAGS = -Wl,--export-dynamic
node_test_LDADD = $(progs_ldadd)
queue_test_LDADD = $(progs_ldadd)
qsort_test_LDADD = $(progs_ldadd)
rand_test_LDADD = $(progs_ldadd)
relation_test_LDADD = $(progs_ldadd)
shell_test_LDADD = $(progs_ldadd)
slist_test_LDADD = $(progs_ldadd)
spawn_test_LDADD = $(progs_ldadd)
strfunc_test_LDADD = $(progs_ldadd)
string_test_LDADD = $(progs_ldadd)
strtod_test_LDADD = $(progs_ldadd) -lm
thread_test_LDADD = $(thread_ldadd)
threadpool_test_LDADD = $(thread_ldadd)
tree_test_LDADD = $(progs_ldadd)
type_test_LDADD = $(progs_ldadd)
unicode_encoding_LDADD = $(progs_ldadd)
unicode_caseconv_LDADD = $(progs_ldadd)
uri_test_LDADD = $(progs_ldadd)

lib_LTLIBRARIES = libmoduletestplugin_a.la libmoduletestplugin_b.la

libmoduletestplugin_a_la_SOURCES = libmoduletestplugin_a.c
libmoduletestplugin_a_la_LDFLAGS = -Wl,--export-dynamic -avoid-version -module $(no_undefined) -rpath $(libdir)
libmoduletestplugin_a_la_LIBADD = -ldl $(libadd_libgmodule) $(libadd_libglib)

libmoduletestplugin_b_la_SOURCES = libmoduletestplugin_b.c
libmoduletestplugin_b_la_LDFLAGS = -Wl,--export-dynamic -avoid-version -module $(no_undefined) -rpath $(libdir)
libmoduletestplugin_b_la_LIBADD = -ldl $(libadd_libgmodule) $(libadd_libglib)
mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_HEADER = ../config.h
CONFIG_CLEAN_FILES = 
LTLIBRARIES =  $(lib_LTLIBRARIES)


DEFS = -DHAVE_CONFIG_H -I. -I$(srcdir) -I..
CPPFLAGS = 
LDFLAGS = 
LIBS =  
libmoduletestplugin_a_la_DEPENDENCIES = 
#libmoduletestplugin_a_la_DEPENDENCIES =  \
#$(top_builddir)/gmodule/libgmodule-2.0.la \
#$(top_builddir)/glib/libglib-2.0.la
libmoduletestplugin_a_la_OBJECTS =  libmoduletestplugin_a.lo
libmoduletestplugin_b_la_DEPENDENCIES = 
#libmoduletestplugin_b_la_DEPENDENCIES =  \
#$(top_builddir)/gmodule/libgmodule-2.0.la \
#$(top_builddir)/glib/libglib-2.0.la
libmoduletestplugin_b_la_OBJECTS =  libmoduletestplugin_b.lo
#check_PROGRAMS =  array-test$(EXEEXT) cxx-test$(EXEEXT) \
#date-test$(EXEEXT) dirname-test$(EXEEXT) \
#gio-test$(EXEEXT) hash-test$(EXEEXT) \
#iochannel-test$(EXEEXT) list-test$(EXEEXT) \
#mainloop-test$(EXEEXT) module-test$(EXEEXT) \
#node-test$(EXEEXT) queue-test$(EXEEXT) \
#qsort-test$(EXEEXT) rand-test$(EXEEXT) \
#relation-test$(EXEEXT) shell-test$(EXEEXT) \
#slist-test$(EXEEXT) spawn-test$(EXEEXT) \
#strfunc-test$(EXEEXT) string-test$(EXEEXT) \
#strtod-test$(EXEEXT) thread-test$(EXEEXT) \
#threadpool-test$(EXEEXT) tree-test$(EXEEXT) \
#type-test$(EXEEXT) unicode-caseconv$(EXEEXT) \
#unicode-encoding$(EXEEXT) uri-test$(EXEEXT) \
#markup-test$(EXEEXT)
check_PROGRAMS =  array-test$(EXEEXT) date-test$(EXEEXT) \
dirname-test$(EXEEXT) gio-test$(EXEEXT) \
hash-test$(EXEEXT) iochannel-test$(EXEEXT) \
list-test$(EXEEXT) mainloop-test$(EXEEXT) \
module-test$(EXEEXT) node-test$(EXEEXT) \
queue-test$(EXEEXT) qsort-test$(EXEEXT) \
rand-test$(EXEEXT) relation-test$(EXEEXT) \
shell-test$(EXEEXT) slist-test$(EXEEXT) \
spawn-test$(EXEEXT) strfunc-test$(EXEEXT) \
string-test$(EXEEXT) strtod-test$(EXEEXT) \
thread-test$(EXEEXT) threadpool-test$(EXEEXT) \
tree-test$(EXEEXT) type-test$(EXEEXT) \
unicode-caseconv$(EXEEXT) unicode-encoding$(EXEEXT) \
uri-test$(EXEEXT) markup-test$(EXEEXT)
#noinst_PROGRAMS =  testglib$(EXEEXT) \
#patterntest$(EXEEXT) testgdate$(EXEEXT) \
#testgdateparser$(EXEEXT) \
#unicode-normalize$(EXEEXT) \
#unicode-collate$(EXEEXT)
noinst_PROGRAMS =  testglib$(EXEEXT) \
patterntest$(EXEEXT) testgdate$(EXEEXT) \
testgdateparser$(EXEEXT) \
unicode-normalize$(EXEEXT) \
unicode-collate$(EXEEXT) timeloop$(EXEEXT) \
timeloop-closure$(EXEEXT)
PROGRAMS =  $(noinst_PROGRAMS)

array_test_SOURCES = array-test.c
array_test_OBJECTS =  array-test.$(OBJEXT)
array_test_DEPENDENCIES =  $(top_builddir)/glib/libglib-2.0.la
array_test_LDFLAGS = 
#cxx_test_OBJECTS =  cxx-test.$(OBJEXT)
#cxx_test_DEPENDENCIES =  \
#$(top_builddir)/glib/libglib-2.0.la
cxx_test_LDFLAGS = 
date_test_SOURCES = date-test.c
date_test_OBJECTS =  date-test.$(OBJEXT)
date_test_DEPENDENCIES =  $(top_builddir)/glib/libglib-2.0.la
date_test_LDFLAGS = 
dirname_test_SOURCES = dirname-test.c
dirname_test_OBJECTS =  dirname-test.$(OBJEXT)
dirname_test_DEPENDENCIES =  $(top_builddir)/glib/libglib-2.0.la
dirname_test_LDFLAGS = 
gio_test_SOURCES = gio-test.c
gio_test_OBJECTS =  gio-test.$(OBJEXT)
gio_test_DEPENDENCIES =  $(top_builddir)/glib/libglib-2.0.la
gio_test_LDFLAGS = 
hash_test_SOURCES = hash-test.c
hash_test_OBJECTS =  hash-test.$(OBJEXT)
hash_test_DEPENDENCIES =  $(top_builddir)/glib/libglib-2.0.la
hash_test_LDFLAGS = 
iochannel_test_SOURCES = iochannel-test.c
iochannel_test_OBJECTS =  iochannel-test.$(OBJEXT)
iochannel_test_DEPENDENCIES =  $(top_builddir)/glib/libglib-2.0.la
iochannel_test_LDFLAGS = 
list_test_SOURCES = list-test.c
list_test_OBJECTS =  list-test.$(OBJEXT)
list_test_DEPENDENCIES =  $(top_builddir)/glib/libglib-2.0.la
list_test_LDFLAGS = 
mainloop_test_SOURCES = mainloop-test.c
mainloop_test_OBJECTS =  mainloop-test.$(OBJEXT)
mainloop_test_DEPENDENCIES =  $(top_builddir)/gthread/libgthread-2.0.la \
$(top_builddir)/glib/libglib-2.0.la
mainloop_test_LDFLAGS = 
module_test_SOURCES = module-test.c
module_test_OBJECTS =  module-test.$(OBJEXT)
module_test_DEPENDENCIES =  \
$(top_builddir)/gmodule/libgmodule-2.0.la \
$(top_builddir)/glib/libglib-2.0.la
#module_test_DEPENDENCIES =  \
#$(top_builddir)/gmodule/libgmodule-2.0.la \
#$(top_builddir)/glib/libglib-2.0.la \
#module-test.exp
node_test_SOURCES = node-test.c
node_test_OBJECTS =  node-test.$(OBJEXT)
node_test_DEPENDENCIES =  $(top_builddir)/glib/libglib-2.0.la
node_test_LDFLAGS = 
queue_test_SOURCES = queue-test.c
queue_test_OBJECTS =  queue-test.$(OBJEXT)
queue_test_DEPENDENCIES =  $(top_builddir)/glib/libglib-2.0.la
queue_test_LDFLAGS = 
qsort_test_SOURCES = qsort-test.c
qsort_test_OBJECTS =  qsort-test.$(OBJEXT)
qsort_test_DEPENDENCIES =  $(top_builddir)/glib/libglib-2.0.la
qsort_test_LDFLAGS = 
rand_test_SOURCES = rand-test.c
rand_test_OBJECTS =  rand-test.$(OBJEXT)
rand_test_DEPENDENCIES =  $(top_builddir)/glib/libglib-2.0.la
rand_test_LDFLAGS = 
relation_test_SOURCES = relation-test.c
relation_test_OBJECTS =  relation-test.$(OBJEXT)
relation_test_DEPENDENCIES =  $(top_builddir)/glib/libglib-2.0.la
relation_test_LDFLAGS = 
shell_test_SOURCES = shell-test.c
shell_test_OBJECTS =  shell-test.$(OBJEXT)
shell_test_DEPENDENCIES =  $(top_builddir)/glib/libglib-2.0.la
shell_test_LDFLAGS = 
slist_test_SOURCES = slist-test.c
slist_test_OBJECTS =  slist-test.$(OBJEXT)
slist_test_DEPENDENCIES =  $(top_builddir)/glib/libglib-2.0.la
slist_test_LDFLAGS = 
spawn_test_SOURCES = spawn-test.c
spawn_test_OBJECTS =  spawn-test.$(OBJEXT)
spawn_test_DEPENDENCIES =  $(top_builddir)/glib/libglib-2.0.la
spawn_test_LDFLAGS = 
strfunc_test_SOURCES = strfunc-test.c
strfunc_test_OBJECTS =  strfunc-test.$(OBJEXT)
strfunc_test_DEPENDENCIES =  $(top_builddir)/glib/libglib-2.0.la
strfunc_test_LDFLAGS = 
string_test_SOURCES = string-test.c
string_test_OBJECTS =  string-test.$(OBJEXT)
string_test_DEPENDENCIES =  $(top_builddir)/glib/libglib-2.0.la
string_test_LDFLAGS = 
strtod_test_SOURCES = strtod-test.c
strtod_test_OBJECTS =  strtod-test.$(OBJEXT)
strtod_test_DEPENDENCIES =  $(top_builddir)/glib/libglib-2.0.la
strtod_test_LDFLAGS = 
thread_test_SOURCES = thread-test.c
thread_test_OBJECTS =  thread-test.$(OBJEXT)
thread_test_DEPENDENCIES =  $(top_builddir)/gthread/libgthread-2.0.la \
$(top_builddir)/glib/libglib-2.0.la
thread_test_LDFLAGS = 
threadpool_test_SOURCES = threadpool-test.c
threadpool_test_OBJECTS =  threadpool-test.$(OBJEXT)
threadpool_test_DEPENDENCIES =  \
$(top_builddir)/gthread/libgthread-2.0.la \
$(top_builddir)/glib/libglib-2.0.la
threadpool_test_LDFLAGS = 
tree_test_SOURCES = tree-test.c
tree_test_OBJECTS =  tree-test.$(OBJEXT)
tree_test_DEPENDENCIES =  $(top_builddir)/glib/libglib-2.0.la
tree_test_LDFLAGS = 
type_test_SOURCES = type-test.c
type_test_OBJECTS =  type-test.$(OBJEXT)
type_test_DEPENDENCIES =  $(top_builddir)/glib/libglib-2.0.la
type_test_LDFLAGS = 
unicode_caseconv_SOURCES = unicode-caseconv.c
unicode_caseconv_OBJECTS =  unicode-caseconv.$(OBJEXT)
unicode_caseconv_DEPENDENCIES =  $(top_builddir)/glib/libglib-2.0.la
unicode_caseconv_LDFLAGS = 
unicode_encoding_SOURCES = unicode-encoding.c
unicode_encoding_OBJECTS =  unicode-encoding.$(OBJEXT)
unicode_encoding_DEPENDENCIES =  $(top_builddir)/glib/libglib-2.0.la
unicode_encoding_LDFLAGS = 
uri_test_SOURCES = uri-test.c
uri_test_OBJECTS =  uri-test.$(OBJEXT)
uri_test_DEPENDENCIES =  $(top_builddir)/glib/libglib-2.0.la
uri_test_LDFLAGS = 
markup_test_SOURCES = markup-test.c
markup_test_OBJECTS =  markup-test.$(OBJEXT)
markup_test_DEPENDENCIES =  $(top_builddir)/glib/libglib-2.0.la
markup_test_LDFLAGS = 
testglib_SOURCES = testglib.c
testglib_OBJECTS =  testglib.$(OBJEXT)
testglib_DEPENDENCIES =  $(top_builddir)/glib/libglib-2.0.la
testglib_LDFLAGS = 
patterntest_SOURCES = patterntest.c
patterntest_OBJECTS =  patterntest.$(OBJEXT)
patterntest_DEPENDENCIES =  $(top_builddir)/glib/libglib-2.0.la
patterntest_LDFLAGS = 
testgdate_SOURCES = testgdate.c
testgdate_OBJECTS =  testgdate.$(OBJEXT)
testgdate_DEPENDENCIES =  $(top_builddir)/glib/libglib-2.0.la
testgdate_LDFLAGS = 
testgdateparser_SOURCES = testgdateparser.c
testgdateparser_OBJECTS =  testgdateparser.$(OBJEXT)
testgdateparser_DEPENDENCIES =  $(top_builddir)/glib/libglib-2.0.la
testgdateparser_LDFLAGS = 
unicode_normalize_SOURCES = unicode-normalize.c
unicode_normalize_OBJECTS =  unicode-normalize.$(OBJEXT)
unicode_normalize_DEPENDENCIES =  $(top_builddir)/glib/libglib-2.0.la
unicode_normalize_LDFLAGS = 
unicode_collate_SOURCES = unicode-collate.c
unicode_collate_OBJECTS =  unicode-collate.$(OBJEXT)
unicode_collate_DEPENDENCIES =  $(top_builddir)/glib/libglib-2.0.la
unicode_collate_LDFLAGS = 
timeloop_SOURCES = timeloop.c
timeloop_OBJECTS =  timeloop.$(OBJEXT)
timeloop_DEPENDENCIES =  \
$(top_builddir)/glib/libglib-2.0.la
timeloop_LDFLAGS = 
timeloop_closure_SOURCES = timeloop-closure.c
timeloop_closure_OBJECTS =  timeloop-closure.$(OBJEXT)
timeloop_closure_DEPENDENCIES =  \
$(top_builddir)/glib/libglib-2.0.la \
$(top_builddir)/gobject/libgobject-2.0.la
timeloop_closure_LDFLAGS = 
CXXFLAGS = 
CXXCOMPILE = $(CXX) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
LTCXXCOMPILE = $(LIBTOOL) --mode=compile $(CXX) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
CXXLD = $(CXX)
CXXLINK = $(LIBTOOL) --mode=link $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(LDFLAGS) -o $@
CFLAGS = -g -O2 -Wall -D_REENTRANT
COMPILE = $(CC) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) --mode=compile $(CC) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(LIBTOOL) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(LDFLAGS) -o $@
DIST_COMMON =  Makefile.am Makefile.in


DISTFILES = $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST)

TAR = gtar
GZIP_ENV = --best
SOURCES = $(libmoduletestplugin_a_la_SOURCES) $(libmoduletestplugin_b_la_SOURCES) array-test.c $(cxx_test_SOURCES) date-test.c dirname-test.c gio-test.c hash-test.c iochannel-test.c list-test.c mainloop-test.c module-test.c node-test.c queue-test.c qsort-test.c rand-test.c relation-test.c shell-test.c slist-test.c spawn-test.c strfunc-test.c string-test.c strtod-test.c thread-test.c threadpool-test.c tree-test.c type-test.c unicode-caseconv.c unicode-encoding.c uri-test.c markup-test.c testglib.c patterntest.c testgdate.c testgdateparser.c unicode-normalize.c unicode-collate.c timeloop.c timeloop-closure.c
OBJECTS = $(libmoduletestplugin_a_la_OBJECTS) $(libmoduletestplugin_b_la_OBJECTS) array-test.$(OBJEXT) $(cxx_test_OBJECTS) date-test.$(OBJEXT) dirname-test.$(OBJEXT) gio-test.$(OBJEXT) hash-test.$(OBJEXT) iochannel-test.$(OBJEXT) list-test.$(OBJEXT) mainloop-test.$(OBJEXT) module-test.$(OBJEXT) node-test.$(OBJEXT) queue-test.$(OBJEXT) qsort-test.$(OBJEXT) rand-test.$(OBJEXT) relation-test.$(OBJEXT) shell-test.$(OBJEXT) slist-test.$(OBJEXT) spawn-test.$(OBJEXT) strfunc-test.$(OBJEXT) string-test.$(OBJEXT) strtod-test.$(OBJEXT) thread-test.$(OBJEXT) threadpool-test.$(OBJEXT) tree-test.$(OBJEXT) type-test.$(OBJEXT) unicode-caseconv.$(OBJEXT) unicode-encoding.$(OBJEXT) uri-test.$(OBJEXT) markup-test.$(OBJEXT) testglib.$(OBJEXT) patterntest.$(OBJEXT) testgdate.$(OBJEXT) testgdateparser.$(OBJEXT) unicode-normalize.$(OBJEXT) unicode-collate.$(OBJEXT) timeloop.$(OBJEXT) timeloop-closure.$(OBJEXT)

all: all-redirect
.SUFFIXES:
.SUFFIXES: .C .S .c .lo .o .obj .s
$(srcdir)/Makefile.in: # Makefile.am $(top_srcdir)/configure.in $(ACLOCAL_M4) 
	cd $(top_srcdir) && $(AUTOMAKE) --gnu --include-deps tests/Makefile

Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status
	cd $(top_builddir) \
	  && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status


mostlyclean-libLTLIBRARIES:

clean-libLTLIBRARIES:
	-test -z "$(lib_LTLIBRARIES)" || rm -f $(lib_LTLIBRARIES)

distclean-libLTLIBRARIES:

maintainer-clean-libLTLIBRARIES:

uninstall-libLTLIBRARIES:
	@$(NORMAL_UNINSTALL)
	list='$(lib_LTLIBRARIES)'; for p in $$list; do \
	  $(LIBTOOL)  --mode=uninstall rm -f $(DESTDIR)$(libdir)/$$p; \
	done

.c.o:
	$(COMPILE) -c $<

# FIXME: We should only use cygpath when building on Windows,
# and only if it is available.
.c.obj:
	$(COMPILE) -c `cygpath -w $<`

.s.o:
	$(COMPILE) -c $<

.S.o:
	$(COMPILE) -c $<

mostlyclean-compile:
	-rm -f *.o core *.core
	-rm -f *.$(OBJEXT)

clean-compile:

distclean-compile:
	-rm -f *.tab.c

maintainer-clean-compile:

.c.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

.s.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

.S.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:

maintainer-clean-libtool:

libmoduletestplugin_a.la: $(libmoduletestplugin_a_la_OBJECTS) $(libmoduletestplugin_a_la_DEPENDENCIES)
	$(LINK) -rpath $(libdir) $(libmoduletestplugin_a_la_LDFLAGS) $(libmoduletestplugin_a_la_OBJECTS) $(libmoduletestplugin_a_la_LIBADD) $(LIBS)

libmoduletestplugin_b.la: $(libmoduletestplugin_b_la_OBJECTS) $(libmoduletestplugin_b_la_DEPENDENCIES)
	$(LINK) -rpath $(libdir) $(libmoduletestplugin_b_la_LDFLAGS) $(libmoduletestplugin_b_la_OBJECTS) $(libmoduletestplugin_b_la_LIBADD) $(LIBS)

mostlyclean-checkPROGRAMS:

clean-checkPROGRAMS:
	-test -z "$(check_PROGRAMS)" || rm -f $(check_PROGRAMS)

distclean-checkPROGRAMS:

maintainer-clean-checkPROGRAMS:

mostlyclean-noinstPROGRAMS:

clean-noinstPROGRAMS:
	-test -z "$(noinst_PROGRAMS)" || rm -f $(noinst_PROGRAMS)

distclean-noinstPROGRAMS:

maintainer-clean-noinstPROGRAMS:

array-test$(EXEEXT): $(array_test_OBJECTS) $(array_test_DEPENDENCIES)
	@rm -f array-test$(EXEEXT)
	$(LINK) $(array_test_LDFLAGS) $(array_test_OBJECTS) $(array_test_LDADD) $(LIBS)

cxx-test$(EXEEXT): $(cxx_test_OBJECTS) $(cxx_test_DEPENDENCIES)
	@rm -f cxx-test$(EXEEXT)
	$(CXXLINK) $(cxx_test_LDFLAGS) $(cxx_test_OBJECTS) $(cxx_test_LDADD) $(LIBS)

date-test$(EXEEXT): $(date_test_OBJECTS) $(date_test_DEPENDENCIES)
	@rm -f date-test$(EXEEXT)
	$(LINK) $(date_test_LDFLAGS) $(date_test_OBJECTS) $(date_test_LDADD) $(LIBS)

dirname-test$(EXEEXT): $(dirname_test_OBJECTS) $(dirname_test_DEPENDENCIES)
	@rm -f dirname-test$(EXEEXT)
	$(LINK) $(dirname_test_LDFLAGS) $(dirname_test_OBJECTS) $(dirname_test_LDADD) $(LIBS)

gio-test$(EXEEXT): $(gio_test_OBJECTS) $(gio_test_DEPENDENCIES)
	@rm -f gio-test$(EXEEXT)
	$(LINK) $(gio_test_LDFLAGS) $(gio_test_OBJECTS) $(gio_test_LDADD) $(LIBS)

hash-test$(EXEEXT): $(hash_test_OBJECTS) $(hash_test_DEPENDENCIES)
	@rm -f hash-test$(EXEEXT)
	$(LINK) $(hash_test_LDFLAGS) $(hash_test_OBJECTS) $(hash_test_LDADD) $(LIBS)

iochannel-test$(EXEEXT): $(iochannel_test_OBJECTS) $(iochannel_test_DEPENDENCIES)
	@rm -f iochannel-test$(EXEEXT)
	$(LINK) $(iochannel_test_LDFLAGS) $(iochannel_test_OBJECTS) $(iochannel_test_LDADD) $(LIBS)

list-test$(EXEEXT): $(list_test_OBJECTS) $(list_test_DEPENDENCIES)
	@rm -f list-test$(EXEEXT)
	$(LINK) $(list_test_LDFLAGS) $(list_test_OBJECTS) $(list_test_LDADD) $(LIBS)

mainloop-test$(EXEEXT): $(mainloop_test_OBJECTS) $(mainloop_test_DEPENDENCIES)
	@rm -f mainloop-test$(EXEEXT)
	$(LINK) $(mainloop_test_LDFLAGS) $(mainloop_test_OBJECTS) $(mainloop_test_LDADD) $(LIBS)

module-test$(EXEEXT): $(module_test_OBJECTS) $(module_test_DEPENDENCIES)
	@rm -f module-test$(EXEEXT)
	$(LINK) $(module_test_LDFLAGS) $(module_test_OBJECTS) $(module_test_LDADD) $(LIBS)

node-test$(EXEEXT): $(node_test_OBJECTS) $(node_test_DEPENDENCIES)
	@rm -f node-test$(EXEEXT)
	$(LINK) $(node_test_LDFLAGS) $(node_test_OBJECTS) $(node_test_LDADD) $(LIBS)

queue-test$(EXEEXT): $(queue_test_OBJECTS) $(queue_test_DEPENDENCIES)
	@rm -f queue-test$(EXEEXT)
	$(LINK) $(queue_test_LDFLAGS) $(queue_test_OBJECTS) $(queue_test_LDADD) $(LIBS)

qsort-test$(EXEEXT): $(qsort_test_OBJECTS) $(qsort_test_DEPENDENCIES)
	@rm -f qsort-test$(EXEEXT)
	$(LINK) $(qsort_test_LDFLAGS) $(qsort_test_OBJECTS) $(qsort_test_LDADD) $(LIBS)

rand-test$(EXEEXT): $(rand_test_OBJECTS) $(rand_test_DEPENDENCIES)
	@rm -f rand-test$(EXEEXT)
	$(LINK) $(rand_test_LDFLAGS) $(rand_test_OBJECTS) $(rand_test_LDADD) $(LIBS)

relation-test$(EXEEXT): $(relation_test_OBJECTS) $(relation_test_DEPENDENCIES)
	@rm -f relation-test$(EXEEXT)
	$(LINK) $(relation_test_LDFLAGS) $(relation_test_OBJECTS) $(relation_test_LDADD) $(LIBS)

shell-test$(EXEEXT): $(shell_test_OBJECTS) $(shell_test_DEPENDENCIES)
	@rm -f shell-test$(EXEEXT)
	$(LINK) $(shell_test_LDFLAGS) $(shell_test_OBJECTS) $(shell_test_LDADD) $(LIBS)

slist-test$(EXEEXT): $(slist_test_OBJECTS) $(slist_test_DEPENDENCIES)
	@rm -f slist-test$(EXEEXT)
	$(LINK) $(slist_test_LDFLAGS) $(slist_test_OBJECTS) $(slist_test_LDADD) $(LIBS)

spawn-test$(EXEEXT): $(spawn_test_OBJECTS) $(spawn_test_DEPENDENCIES)
	@rm -f spawn-test$(EXEEXT)
	$(LINK) $(spawn_test_LDFLAGS) $(spawn_test_OBJECTS) $(spawn_test_LDADD) $(LIBS)

strfunc-test$(EXEEXT): $(strfunc_test_OBJECTS) $(strfunc_test_DEPENDENCIES)
	@rm -f strfunc-test$(EXEEXT)
	$(LINK) $(strfunc_test_LDFLAGS) $(strfunc_test_OBJECTS) $(strfunc_test_LDADD) $(LIBS)

string-test$(EXEEXT): $(string_test_OBJECTS) $(string_test_DEPENDENCIES)
	@rm -f string-test$(EXEEXT)
	$(LINK) $(string_test_LDFLAGS) $(string_test_OBJECTS) $(string_test_LDADD) $(LIBS)

strtod-test$(EXEEXT): $(strtod_test_OBJECTS) $(strtod_test_DEPENDENCIES)
	@rm -f strtod-test$(EXEEXT)
	$(LINK) $(strtod_test_LDFLAGS) $(strtod_test_OBJECTS) $(strtod_test_LDADD) $(LIBS)

thread-test$(EXEEXT): $(thread_test_OBJECTS) $(thread_test_DEPENDENCIES)
	@rm -f thread-test$(EXEEXT)
	$(LINK) $(thread_test_LDFLAGS) $(thread_test_OBJECTS) $(thread_test_LDADD) $(LIBS)

threadpool-test$(EXEEXT): $(threadpool_test_OBJECTS) $(threadpool_test_DEPENDENCIES)
	@rm -f threadpool-test$(EXEEXT)
	$(LINK) $(threadpool_test_LDFLAGS) $(threadpool_test_OBJECTS) $(threadpool_test_LDADD) $(LIBS)

tree-test$(EXEEXT): $(tree_test_OBJECTS) $(tree_test_DEPENDENCIES)
	@rm -f tree-test$(EXEEXT)
	$(LINK) $(tree_test_LDFLAGS) $(tree_test_OBJECTS) $(tree_test_LDADD) $(LIBS)

type-test$(EXEEXT): $(type_test_OBJECTS) $(type_test_DEPENDENCIES)
	@rm -f type-test$(EXEEXT)
	$(LINK) $(type_test_LDFLAGS) $(type_test_OBJECTS) $(type_test_LDADD) $(LIBS)

unicode-caseconv$(EXEEXT): $(unicode_caseconv_OBJECTS) $(unicode_caseconv_DEPENDENCIES)
	@rm -f unicode-caseconv$(EXEEXT)
	$(LINK) $(unicode_caseconv_LDFLAGS) $(unicode_caseconv_OBJECTS) $(unicode_caseconv_LDADD) $(LIBS)

unicode-encoding$(EXEEXT): $(unicode_encoding_OBJECTS) $(unicode_encoding_DEPENDENCIES)
	@rm -f unicode-encoding$(EXEEXT)
	$(LINK) $(unicode_encoding_LDFLAGS) $(unicode_encoding_OBJECTS) $(unicode_encoding_LDADD) $(LIBS)

uri-test$(EXEEXT): $(uri_test_OBJECTS) $(uri_test_DEPENDENCIES)
	@rm -f uri-test$(EXEEXT)
	$(LINK) $(uri_test_LDFLAGS) $(uri_test_OBJECTS) $(uri_test_LDADD) $(LIBS)

markup-test$(EXEEXT): $(markup_test_OBJECTS) $(markup_test_DEPENDENCIES)
	@rm -f markup-test$(EXEEXT)
	$(LINK) $(markup_test_LDFLAGS) $(markup_test_OBJECTS) $(markup_test_LDADD) $(LIBS)

testglib$(EXEEXT): $(testglib_OBJECTS) $(testglib_DEPENDENCIES)
	@rm -f testglib$(EXEEXT)
	$(LINK) $(testglib_LDFLAGS) $(testglib_OBJECTS) $(testglib_LDADD) $(LIBS)

patterntest$(EXEEXT): $(patterntest_OBJECTS) $(patterntest_DEPENDENCIES)
	@rm -f patterntest$(EXEEXT)
	$(LINK) $(patterntest_LDFLAGS) $(patterntest_OBJECTS) $(patterntest_LDADD) $(LIBS)

testgdate$(EXEEXT): $(testgdate_OBJECTS) $(testgdate_DEPENDENCIES)
	@rm -f testgdate$(EXEEXT)
	$(LINK) $(testgdate_LDFLAGS) $(testgdate_OBJECTS) $(testgdate_LDADD) $(LIBS)

testgdateparser$(EXEEXT): $(testgdateparser_OBJECTS) $(testgdateparser_DEPENDENCIES)
	@rm -f testgdateparser$(EXEEXT)
	$(LINK) $(testgdateparser_LDFLAGS) $(testgdateparser_OBJECTS) $(testgdateparser_LDADD) $(LIBS)

unicode-normalize$(EXEEXT): $(unicode_normalize_OBJECTS) $(unicode_normalize_DEPENDENCIES)
	@rm -f unicode-normalize$(EXEEXT)
	$(LINK) $(unicode_normalize_LDFLAGS) $(unicode_normalize_OBJECTS) $(unicode_normalize_LDADD) $(LIBS)

unicode-collate$(EXEEXT): $(unicode_collate_OBJECTS) $(unicode_collate_DEPENDENCIES)
	@rm -f unicode-collate$(EXEEXT)
	$(LINK) $(unicode_collate_LDFLAGS) $(unicode_collate_OBJECTS) $(unicode_collate_LDADD) $(LIBS)

timeloop$(EXEEXT): $(timeloop_OBJECTS) $(timeloop_DEPENDENCIES)
	@rm -f timeloop$(EXEEXT)
	$(LINK) $(timeloop_LDFLAGS) $(timeloop_OBJECTS) $(timeloop_LDADD) $(LIBS)

timeloop-closure$(EXEEXT): $(timeloop_closure_OBJECTS) $(timeloop_closure_DEPENDENCIES)
	@rm -f timeloop-closure$(EXEEXT)
	$(LINK) $(timeloop_closure_LDFLAGS) $(timeloop_closure_OBJECTS) $(timeloop_closure_LDADD) $(LIBS)
.C.o:
	$(CXXCOMPILE) -c $<
.C.obj:
	$(CXXCOMPILE) -c `cygpath -w $<`
.C.lo:
	$(LTCXXCOMPILE) -c $<

tags: TAGS

ID: $(HEADERS) $(SOURCES) $(LISP)
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	here=`pwd` && cd $(srcdir) \
	  && mkid -f$$here/ID $$unique $(LISP)

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(ETAGS_ARGS)$$unique$(LISP)$$tags" \
	  || (cd $(srcdir) && etags $(ETAGS_ARGS) $$tags  $$unique $(LISP) -o $$here/TAGS)

mostlyclean-tags:

clean-tags:

distclean-tags:
	-rm -f TAGS ID

maintainer-clean-tags:

distdir = $(top_builddir)/$(PACKAGE)-$(VERSION)/$(subdir)

subdir = tests

distdir: $(DISTFILES)
	@for file in $(DISTFILES); do \
	  d=$(srcdir); \
	  if test -d $$d/$$file; then \
	    cp -pr $$d/$$file $(distdir)/$$file; \
	  else \
	    test -f $(distdir)/$$file \
	    || ln $$d/$$file $(distdir)/$$file 2> /dev/null \
	    || cp -p $$d/$$file $(distdir)/$$file || :; \
	  fi; \
	done
	$(MAKE) $(AM_MAKEFLAGS) top_distdir="$(top_distdir)" distdir="$(distdir)" dist-hook
libmoduletestplugin_a.lo libmoduletestplugin_a.o : \
	libmoduletestplugin_a.c ../gmodule/gmodule.h ../glib/glib.h \
	../glib/galloca.h ../glib/gtypes.h ../glibconfig.h \
	../glib/gmacros.h ../glib/garray.h ../glib/gasyncqueue.h \
	../glib/gthread.h ../glib/gerror.h ../glib/gquark.h \
	../glib/gbacktrace.h ../glib/gcache.h ../glib/glist.h \
	../glib/gmem.h ../glib/gcompletion.h ../glib/gconvert.h \
	../glib/gdataset.h ../glib/gdate.h ../glib/gdir.h \
	../glib/gfileutils.h ../glib/ghash.h ../glib/ghook.h \
	../glib/giochannel.h ../glib/gmain.h ../glib/gslist.h \
	../glib/gstring.h ../glib/gunicode.h ../glib/gmarkup.h \
	../glib/gmessages.h ../glib/gnode.h ../glib/gpattern.h \
	../glib/gprimes.h ../glib/gqsort.h ../glib/gqueue.h \
	../glib/grand.h ../glib/grel.h ../glib/gscanner.h \
	../glib/gshell.h ../glib/gspawn.h ../glib/gstrfuncs.h \
	../glib/gthreadpool.h ../glib/gtimer.h ../glib/gtree.h \
	../glib/gutils.h
libmoduletestplugin_b.lo libmoduletestplugin_b.o : \
	libmoduletestplugin_b.c ../gmodule/gmodule.h ../glib/glib.h \
	../glib/galloca.h ../glib/gtypes.h ../glibconfig.h \
	../glib/gmacros.h ../glib/garray.h ../glib/gasyncqueue.h \
	../glib/gthread.h ../glib/gerror.h ../glib/gquark.h \
	../glib/gbacktrace.h ../glib/gcache.h ../glib/glist.h \
	../glib/gmem.h ../glib/gcompletion.h ../glib/gconvert.h \
	../glib/gdataset.h ../glib/gdate.h ../glib/gdir.h \
	../glib/gfileutils.h ../glib/ghash.h ../glib/ghook.h \
	../glib/giochannel.h ../glib/gmain.h ../glib/gslist.h \
	../glib/gstring.h ../glib/gunicode.h ../glib/gmarkup.h \
	../glib/gmessages.h ../glib/gnode.h ../glib/gpattern.h \
	../glib/gprimes.h ../glib/gqsort.h ../glib/gqueue.h \
	../glib/grand.h ../glib/grel.h ../glib/gscanner.h \
	../glib/gshell.h ../glib/gspawn.h ../glib/gstrfuncs.h \
	../glib/gthreadpool.h ../glib/gtimer.h ../glib/gtree.h \
	../glib/gutils.h
patterntest.o: patterntest.c ../glib/glib.h ../glib/galloca.h \
	../glib/gtypes.h ../glibconfig.h ../glib/gmacros.h \
	../glib/garray.h ../glib/gasyncqueue.h ../glib/gthread.h \
	../glib/gerror.h ../glib/gquark.h ../glib/gbacktrace.h \
	../glib/gcache.h ../glib/glist.h ../glib/gmem.h \
	../glib/gcompletion.h ../glib/gconvert.h ../glib/gdataset.h \
	../glib/gdate.h ../glib/gdir.h ../glib/gfileutils.h \
	../glib/ghash.h ../glib/ghook.h ../glib/giochannel.h \
	../glib/gmain.h ../glib/gslist.h ../glib/gstring.h \
	../glib/gunicode.h ../glib/gmarkup.h ../glib/gmessages.h \
	../glib/gnode.h ../glib/gpattern.h ../glib/gprimes.h \
	../glib/gqsort.h ../glib/gqueue.h ../glib/grand.h \
	../glib/grel.h ../glib/gscanner.h ../glib/gshell.h \
	../glib/gspawn.h ../glib/gstrfuncs.h ../glib/gthreadpool.h \
	../glib/gtimer.h ../glib/gtree.h ../glib/gutils.h
testgdate.o: testgdate.c ../glib/glib.h ../glib/galloca.h \
	../glib/gtypes.h ../glibconfig.h ../glib/gmacros.h \
	../glib/garray.h ../glib/gasyncqueue.h ../glib/gthread.h \
	../glib/gerror.h ../glib/gquark.h ../glib/gbacktrace.h \
	../glib/gcache.h ../glib/glist.h ../glib/gmem.h \
	../glib/gcompletion.h ../glib/gconvert.h ../glib/gdataset.h \
	../glib/gdate.h ../glib/gdir.h ../glib/gfileutils.h \
	../glib/ghash.h ../glib/ghook.h ../glib/giochannel.h \
	../glib/gmain.h ../glib/gslist.h ../glib/gstring.h \
	../glib/gunicode.h ../glib/gmarkup.h ../glib/gmessages.h \
	../glib/gnode.h ../glib/gpattern.h ../glib/gprimes.h \
	../glib/gqsort.h ../glib/gqueue.h ../glib/grand.h \
	../glib/grel.h ../glib/gscanner.h ../glib/gshell.h \
	../glib/gspawn.h ../glib/gstrfuncs.h ../glib/gthreadpool.h \
	../glib/gtimer.h ../glib/gtree.h ../glib/gutils.h
testgdateparser.o: testgdateparser.c ../glib/glib.h ../glib/galloca.h \
	../glib/gtypes.h ../glibconfig.h ../glib/gmacros.h \
	../glib/garray.h ../glib/gasyncqueue.h ../glib/gthread.h \
	../glib/gerror.h ../glib/gquark.h ../glib/gbacktrace.h \
	../glib/gcache.h ../glib/glist.h ../glib/gmem.h \
	../glib/gcompletion.h ../glib/gconvert.h ../glib/gdataset.h \
	../glib/gdate.h ../glib/gdir.h ../glib/gfileutils.h \
	../glib/ghash.h ../glib/ghook.h ../glib/giochannel.h \
	../glib/gmain.h ../glib/gslist.h ../glib/gstring.h \
	../glib/gunicode.h ../glib/gmarkup.h ../glib/gmessages.h \
	../glib/gnode.h ../glib/gpattern.h ../glib/gprimes.h \
	../glib/gqsort.h ../glib/gqueue.h ../glib/grand.h \
	../glib/grel.h ../glib/gscanner.h ../glib/gshell.h \
	../glib/gspawn.h ../glib/gstrfuncs.h ../glib/gthreadpool.h \
	../glib/gtimer.h ../glib/gtree.h ../glib/gutils.h
testglib.o: testglib.c ../config.h ../glib/glib.h ../glib/galloca.h \
	../glib/gtypes.h ../glibconfig.h ../glib/gmacros.h \
	../glib/garray.h ../glib/gasyncqueue.h ../glib/gthread.h \
	../glib/gerror.h ../glib/gquark.h ../glib/gbacktrace.h \
	../glib/gcache.h ../glib/glist.h ../glib/gmem.h \
	../glib/gcompletion.h ../glib/gconvert.h ../glib/gdataset.h \
	../glib/gdate.h ../glib/gdir.h ../glib/gfileutils.h \
	../glib/ghash.h ../glib/ghook.h ../glib/giochannel.h \
	../glib/gmain.h ../glib/gslist.h ../glib/gstring.h \
	../glib/gunicode.h ../glib/gmarkup.h ../glib/gmessages.h \
	../glib/gnode.h ../glib/gpattern.h ../glib/gprimes.h \
	../glib/gqsort.h ../glib/gqueue.h ../glib/grand.h \
	../glib/grel.h ../glib/gscanner.h ../glib/gshell.h \
	../glib/gspawn.h ../glib/gstrfuncs.h ../glib/gthreadpool.h \
	../glib/gtimer.h ../glib/gtree.h ../glib/gutils.h
timeloop-closure.o: timeloop-closure.c ../glib/glib.h ../glib/galloca.h \
	../glib/gtypes.h ../glibconfig.h ../glib/gmacros.h \
	../glib/garray.h ../glib/gasyncqueue.h ../glib/gthread.h \
	../glib/gerror.h ../glib/gquark.h ../glib/gbacktrace.h \
	../glib/gcache.h ../glib/glist.h ../glib/gmem.h \
	../glib/gcompletion.h ../glib/gconvert.h ../glib/gdataset.h \
	../glib/gdate.h ../glib/gdir.h ../glib/gfileutils.h \
	../glib/ghash.h ../glib/ghook.h ../glib/giochannel.h \
	../glib/gmain.h ../glib/gslist.h ../glib/gstring.h \
	../glib/gunicode.h ../glib/gmarkup.h ../glib/gmessages.h \
	../glib/gnode.h ../glib/gpattern.h ../glib/gprimes.h \
	../glib/gqsort.h ../glib/gqueue.h ../glib/grand.h \
	../glib/grel.h ../glib/gscanner.h ../glib/gshell.h \
	../glib/gspawn.h ../glib/gstrfuncs.h ../glib/gthreadpool.h \
	../glib/gtimer.h ../glib/gtree.h ../glib/gutils.h \
	../glib/glib-object.h ../gobject/gboxed.h ../gobject/gtype.h \
	../gobject/genums.h ../gobject/gobject.h ../gobject/gvalue.h \
	../gobject/gparam.h ../gobject/gclosure.h ../gobject/gsignal.h \
	../gobject/gmarshal.h ../gobject/gparamspecs.h \
	../gobject/gsourceclosure.h ../gobject/gtypemodule.h \
	../gobject/gtypeplugin.h ../gobject/gvaluearray.h \
	../gobject/gvaluetypes.h
timeloop.o: timeloop.c ../glib/glib.h ../glib/galloca.h ../glib/gtypes.h \
	../glibconfig.h ../glib/gmacros.h ../glib/garray.h \
	../glib/gasyncqueue.h ../glib/gthread.h ../glib/gerror.h \
	../glib/gquark.h ../glib/gbacktrace.h ../glib/gcache.h \
	../glib/glist.h ../glib/gmem.h ../glib/gcompletion.h \
	../glib/gconvert.h ../glib/gdataset.h ../glib/gdate.h \
	../glib/gdir.h ../glib/gfileutils.h ../glib/ghash.h \
	../glib/ghook.h ../glib/giochannel.h ../glib/gmain.h \
	../glib/gslist.h ../glib/gstring.h ../glib/gunicode.h \
	../glib/gmarkup.h ../glib/gmessages.h ../glib/gnode.h \
	../glib/gpattern.h ../glib/gprimes.h ../glib/gqsort.h \
	../glib/gqueue.h ../glib/grand.h ../glib/grel.h \
	../glib/gscanner.h ../glib/gshell.h ../glib/gspawn.h \
	../glib/gstrfuncs.h ../glib/gthreadpool.h ../glib/gtimer.h \
	../glib/gtree.h ../glib/gutils.h
unicode-collate.o: unicode-collate.c ../glib/glib.h ../glib/galloca.h \
	../glib/gtypes.h ../glibconfig.h ../glib/gmacros.h \
	../glib/garray.h ../glib/gasyncqueue.h ../glib/gthread.h \
	../glib/gerror.h ../glib/gquark.h ../glib/gbacktrace.h \
	../glib/gcache.h ../glib/glist.h ../glib/gmem.h \
	../glib/gcompletion.h ../glib/gconvert.h ../glib/gdataset.h \
	../glib/gdate.h ../glib/gdir.h ../glib/gfileutils.h \
	../glib/ghash.h ../glib/ghook.h ../glib/giochannel.h \
	../glib/gmain.h ../glib/gslist.h ../glib/gstring.h \
	../glib/gunicode.h ../glib/gmarkup.h ../glib/gmessages.h \
	../glib/gnode.h ../glib/gpattern.h ../glib/gprimes.h \
	../glib/gqsort.h ../glib/gqueue.h ../glib/grand.h \
	../glib/grel.h ../glib/gscanner.h ../glib/gshell.h \
	../glib/gspawn.h ../glib/gstrfuncs.h ../glib/gthreadpool.h \
	../glib/gtimer.h ../glib/gtree.h ../glib/gutils.h
unicode-normalize.o: unicode-normalize.c ../glib/glib.h \
	../glib/galloca.h ../glib/gtypes.h ../glibconfig.h \
	../glib/gmacros.h ../glib/garray.h ../glib/gasyncqueue.h \
	../glib/gthread.h ../glib/gerror.h ../glib/gquark.h \
	../glib/gbacktrace.h ../glib/gcache.h ../glib/glist.h \
	../glib/gmem.h ../glib/gcompletion.h ../glib/gconvert.h \
	../glib/gdataset.h ../glib/gdate.h ../glib/gdir.h \
	../glib/gfileutils.h ../glib/ghash.h ../glib/ghook.h \
	../glib/giochannel.h ../glib/gmain.h ../glib/gslist.h \
	../glib/gstring.h ../glib/gunicode.h ../glib/gmarkup.h \
	../glib/gmessages.h ../glib/gnode.h ../glib/gpattern.h \
	../glib/gprimes.h ../glib/gqsort.h ../glib/gqueue.h \
	../glib/grand.h ../glib/grel.h ../glib/gscanner.h \
	../glib/gshell.h ../glib/gspawn.h ../glib/gstrfuncs.h \
	../glib/gthreadpool.h ../glib/gtimer.h ../glib/gtree.h \
	../glib/gutils.h

check-TESTS: $(TESTS)
	@failed=0; all=0; \
	srcdir=$(srcdir); export srcdir; \
	for tst in $(TESTS); do \
	  if test -f $$tst; then dir=.; \
	  else dir="$(srcdir)"; fi; \
	  if $(TESTS_ENVIRONMENT) $$dir/$$tst; then \
	    all=`expr $$all + 1`; \
	    echo "PASS: $$tst"; \
	  elif test $$? -ne 77; then \
	    all=`expr $$all + 1`; \
	    failed=`expr $$failed + 1`; \
	    echo "FAIL: $$tst"; \
	  fi; \
	done; \
	if test "$$failed" -eq 0; then \
	  banner="All $$all tests passed"; \
	else \
	  banner="$$failed of $$all tests failed"; \
	fi; \
	dashes=`echo "$$banner" | sed s/./=/g`; \
	echo "$$dashes"; \
	echo "$$banner"; \
	echo "$$dashes"; \
	test "$$failed" -eq 0
info-am:
info: info-am
dvi-am:
dvi: dvi-am
check-am: all-am
	$(MAKE) $(AM_MAKEFLAGS) $(check_PROGRAMS)
	$(MAKE) $(AM_MAKEFLAGS) check-TESTS
check: check-am
installcheck-am:
installcheck: installcheck-am
install-exec-am: install-libLTLIBRARIES
install-exec: install-exec-am

install-data-am:
install-data: install-data-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am
install: install-am
uninstall-am: uninstall-libLTLIBRARIES
uninstall: uninstall-am
all-am: Makefile $(LTLIBRARIES) $(PROGRAMS)
all-redirect: all-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) AM_INSTALL_PROGRAM_FLAGS=-s install
installdirs:
	$(mkinstalldirs)  $(DESTDIR)$(libdir)


mostlyclean-generic:

clean-generic:

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES)
	-rm -f config.cache config.log stamp-h stamp-h[0-9]*

maintainer-clean-generic:
mostlyclean-am:  mostlyclean-libLTLIBRARIES mostlyclean-compile \
		mostlyclean-libtool mostlyclean-checkPROGRAMS \
		mostlyclean-noinstPROGRAMS mostlyclean-tags \
		mostlyclean-generic

mostlyclean: mostlyclean-am

clean-am:  clean-libLTLIBRARIES clean-compile clean-libtool \
		clean-checkPROGRAMS clean-noinstPROGRAMS clean-tags \
		clean-generic mostlyclean-am

clean: clean-am

distclean-am:  distclean-libLTLIBRARIES distclean-compile \
		distclean-libtool distclean-checkPROGRAMS \
		distclean-noinstPROGRAMS distclean-tags \
		distclean-generic clean-am
	-rm -f libtool

distclean: distclean-am

maintainer-clean-am:  maintainer-clean-libLTLIBRARIES \
		maintainer-clean-compile maintainer-clean-libtool \
		maintainer-clean-checkPROGRAMS \
		maintainer-clean-noinstPROGRAMS maintainer-clean-tags \
		maintainer-clean-generic distclean-am
	@echo "This command is intended for maintainers to use;"
	@echo "it deletes files that may require special tools to rebuild."

maintainer-clean: maintainer-clean-am

.PHONY: mostlyclean-libLTLIBRARIES distclean-libLTLIBRARIES \
clean-libLTLIBRARIES maintainer-clean-libLTLIBRARIES \
uninstall-libLTLIBRARIES install-libLTLIBRARIES mostlyclean-compile \
distclean-compile clean-compile maintainer-clean-compile \
mostlyclean-libtool distclean-libtool clean-libtool \
maintainer-clean-libtool mostlyclean-checkPROGRAMS \
distclean-checkPROGRAMS clean-checkPROGRAMS \
maintainer-clean-checkPROGRAMS mostlyclean-noinstPROGRAMS \
distclean-noinstPROGRAMS clean-noinstPROGRAMS \
maintainer-clean-noinstPROGRAMS tags mostlyclean-tags distclean-tags \
clean-tags maintainer-clean-tags distdir check-TESTS info-am info \
dvi-am dvi check check-am installcheck-am installcheck install-exec-am \
install-exec install-data-am install-data install-am install \
uninstall-am uninstall all-redirect all-am all installdirs \
mostlyclean-generic distclean-generic clean-generic \
maintainer-clean-generic clean mostlyclean distclean maintainer-clean


#module-test.exp: module-test.o
#	dlltool --output-exp module-test.exp module-test.o

# Prevent those libs from being installed
install-libLTLIBRARIES:
	:

makefile.mingw: $(top_builddir)/config.status $(top_srcdir)/tests/makefile.mingw.in
	cd $(top_builddir) && CONFIG_FILES=tests/$@ CONFIG_HEADERS= $(SHELL) ./config.status

makefile.msc: $(top_builddir)/config.status $(top_srcdir)/tests/makefile.msc.in
	cd $(top_builddir) && CONFIG_FILES=tests/$@ CONFIG_HEADERS= $(SHELL) ./config.status

dist-hook: $(BUILT_EXTRA_DIST)
	files='$(BUILT_EXTRA_DIST)'; \
	for f in $$files; do \
	  if test -f $$f; then d=.; else d=$(srcdir); fi; \
	  cp $$d/$$f $(distdir) || exit 1; done
	mkdir $(distdir)/markups;          \
	for f in $(srcdir)/markups/* ; do  \
	  cp $$f $(distdir)/markups;       \
	done

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
