# Makefile.in generated automatically by automake 1.4-p6 from Makefile.am

# Copyright (C) 1994, 1995-8, 1999, 2001 Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.


SHELL = /bin/sh

srcdir = .
top_srcdir = ..

prefix = /usr/local
exec_prefix = ${prefix}

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include

DESTDIR =

pkgdatadir = $(datadir)/glib
pkglibdir = $(libdir)/glib
pkgincludedir = $(includedir)/glib

top_builddir = ..

ACLOCAL = /home/general/cn_proc/glib-2.0.7/missing aclocal-1.4
AUTOCONF = /home/general/cn_proc/glib-2.0.7/missing autoconf
AUTOMAKE = /home/general/cn_proc/glib-2.0.7/missing automake-1.4
AUTOHEADER = /home/general/cn_proc/glib-2.0.7/missing autoheader

INSTALL = /usr/bin/install -c
INSTALL_PROGRAM = ${INSTALL} $(AM_INSTALL_PROGRAM_FLAGS)
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL}
transform = s,x,x,

NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
host_alias = 
host_triplet = x86_64-unknown-linux-gnu
AS = @AS@
AWK = gawk
CATALOGS =  ar.gmo az.gmo be.gmo bg.gmo ca.gmo cs.gmo de.gmo el.gmo es.gmo eu.gmo fr.gmo gl.gmo ja.gmo ko.gmo ms.gmo nl.gmo nn.gmo no.gmo pl.gmo pt.gmo pt_BR.gmo ro.gmo ru.gmo sk.gmo sl.gmo sv.gmo ta.gmo tr.gmo uk.gmo vi.gmo zh_CN.gmo zh_TW.gmo
CATOBJEXT = .gmo
CC = gcc
CXX = 
DATADIRNAME = share
DB2HTML = false
DISABLE_MEM_POOLS = 
DLLTOOL = @DLLTOOL@
ECHO = echo
ENABLE_GC_FRIENDLY = 
EXEEXT = 
GETTEXT_PACKAGE = glib20
GIO = giounix.lo
GLIBC21 = yes
GLIB_BINARY_AGE = 7
GLIB_DEBUG_FLAGS = 
GLIB_DEF = 
GLIB_GENMARSHAL = 
GLIB_INTERFACE_AGE = 7
GLIB_MAJOR_VERSION = 2
GLIB_MICRO_VERSION = 7
GLIB_MINOR_VERSION = 0
GLIB_VERSION = 2.0.7
GMODULE_DEF = 
GMOFILES =  ar.gmo az.gmo be.gmo bg.gmo ca.gmo cs.gmo de.gmo el.gmo es.gmo eu.gmo fr.gmo gl.gmo ja.gmo ko.gmo ms.gmo nl.gmo nn.gmo no.gmo pl.gmo pt.gmo pt_BR.gmo ro.gmo ru.gmo sk.gmo sl.gmo sv.gmo ta.gmo tr.gmo uk.gmo vi.gmo zh_CN.gmo zh_TW.gmo
GMSGFMT = /usr/bin/msgfmt
GOBJECT_DEF = 
GSPAWN = gspawn.lo
GTHREAD_COMPILE_IMPL_DEFINES = -D_POSIX4_DRAFT_SOURCE -D_POSIX4A_DRAFT10_SOURCE -U_OSF_SOURCE
GTHREAD_DEF = 
GTKDOC = false
G_LIBS_EXTRA = 
G_LIB_WIN32_RESOURCE = 
G_MODULE_BROKEN_RTLD_GLOBAL = 0
G_MODULE_HAVE_DLERROR = 1
G_MODULE_IMPL = G_MODULE_IMPL_DL
G_MODULE_LDFLAGS = -Wl,--export-dynamic
G_MODULE_LIBS = -ldl
G_MODULE_LIBS_EXTRA = 
G_MODULE_NEED_USCORE = 0
G_MODULE_PLUGIN_LIBS = 
G_MODULE_SUPPORTED = true
G_MODULE_WIN32_RESOURCE = 
G_OBJECT_WIN32_RESOURCE = 
G_THREAD_CFLAGS = -D_REENTRANT
G_THREAD_LIBS = -lpthread 
G_THREAD_LIBS_EXTRA = 
G_THREAD_WIN32_RESOURCE = 
HAVE_GTK_DOC = 
HTML_DIR = ${datadir}/gtk-doc/html
ICONV_LIBS = 
INDENT = 
INSTOBJEXT = .mo
INTLDEPS = 
INTLLIBS = 
INTLOBJS = 
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LN_S = ln -s
LT_AGE = 0
LT_CURRENT = 0
LT_CURRENT_MINUS_AGE = 0
LT_RELEASE = 2.0
LT_REVISION = 7
MAINT = #
MAKEINFO = /home/general/cn_proc/glib-2.0.7/missing makeinfo
MKINSTALLDIRS = ./mkinstalldirs
OBJDUMP = @OBJDUMP@
OBJEXT = o
PACKAGE = glib
PERL = perl
PERL_PATH = /usr/bin/perl
PKG_CONFIG = /usr/bin/pkg-config
PLATFORMDEP = 
POFILES =  ar.po az.po be.po bg.po ca.po cs.po de.po el.po es.po eu.po fr.po gl.po ja.po ko.po ms.po nl.po nn.po no.po pl.po pt.po pt_BR.po ro.po ru.po sk.po sl.po sv.po ta.po tr.po uk.po vi.po zh_CN.po zh_TW.po
POSUB = po
RANLIB = ranlib
REBUILD = 
STRIP = strip
STRIP_BEGIN = $(strip $(STRIP_DUMMY)
STRIP_DUMMY = 
STRIP_END = )
TESTGMODULE_EXP = 
USE_NLS = yes
VERSION = 2.0.7
ms_librarian = 

SUBDIRS = libcharset

INCLUDES = -I$(top_srcdir) -DG_LOG_DOMAIN=\"GLib\" \
	 -DG_DISABLE_DEPRECATED -DGLIB_COMPILATION 


EXTRA_DIST = \
	makefile.mingw.in	\
	makefile.msc.in		\
	glib.rc.in		\
	gen-unicode-tables.pl	\
	glib.def


# These may be in the builddir too
BUILT_EXTRA_DIST = \
	makefile.msc		\
	makefile.mingw		\
	glib.rc


lib_LTLIBRARIES = libglib-2.0.la

#noinst_DATA = #glib-2.0.lib

libglib_2_0_la_SOURCES = \
	garray.c		\
	gasyncqueue.c		\
	gbacktrace.c		\
	gbsearcharray.c		\
	gbsearcharray.h		\
	gcache.c		\
	gcompletion.c		\
	gconvert.c		\
	gdataset.c		\
	gdate.c         	\
	gdir.c			\
	gerror.c		\
	gfileutils.c		\
	ghash.c			\
	ghook.c			\
	giochannel.c    	\
	glibintl.h		\
	glist.c			\
	gmain.c         	\
	gmarkup.c		\
	gmem.c			\
	gmessages.c		\
	gnode.c			\
	gpattern.c		\
	gprimes.c		\
	gqsort.c		\
	gqueue.c		\
	grel.c			\
	grand.c			\
	gscanner.c		\
	gshell.c		\
	gslist.c		\
	gstrfuncs.c		\
	gstring.c		\
	gthread.c       	\
	gthreadpool.c   	\
	gtimer.c		\
	gtree.c			\
	guniprop.c		\
	gutf8.c			\
	gunibreak.h		\
	gunibreak.c		\
	gunichartables.h	\
	gunicollate.c		\
	gunicomp.h		\
	gunidecomp.h		\
	gunidecomp.c		\
	gutils.c		\
	gdebug.h


EXTRA_libglib_2_0_la_SOURCES = \
	giounix.c	\
	giowin32.c	\
	gspawn.c	\
	gspawn-win32.c	\
	gwin32.c


glibincludedir = $(includedir)/glib-2.0
glibinclude_HEADERS = \
	glib-object.h	\
	glib.h


glibsubincludedir = $(includedir)/glib-2.0/glib
glibsubinclude_HEADERS = \
	galloca.h	\
	garray.h	\
	gasyncqueue.h	\
	gbacktrace.h	\
	gcache.h	\
	gcompletion.h	\
	gconvert.h	\
	gdataset.h	\
	gdate.h		\
	gdir.h		\
	gerror.h	\
	gfileutils.h	\
	ghash.h		\
	ghook.h		\
	giochannel.h	\
	glist.h		\
	gmacros.h	\
	gmain.h		\
	gmarkup.h	\
	gmem.h		\
	gmessages.h	\
	gnode.h		\
	gpattern.h	\
	gprimes.h	\
	gqsort.h	\
	gquark.h	\
	gqueue.h	\
	grand.h		\
	grel.h		\
	gscanner.h	\
	gshell.h	\
	gslist.h	\
	gspawn.h	\
	gstrfuncs.h	\
	gstring.h	\
	gthread.h	\
	gthreadpool.h	\
	gtimer.h	\
	gtree.h		\
	gtypes.h	\
	gunicode.h	\
	gutils.h	\
	gwin32.h


#no_undefined = #-no-undefined

# This requires a very new libtool
#export_symbols = #-export-symbols glib.def

libglib_2_0_la_LIBADD = libcharset/libcharset.la giounix.lo gspawn.lo     
libglib_2_0_la_DEPENDENCIES = libcharset/libcharset.la giounix.lo gspawn.lo   

libglib_2_0_la_LDFLAGS = \
	-version-info $(LT_CURRENT):$(LT_REVISION):$(LT_AGE) \
	-export-dynamic $(no_undefined) $(export_symbols)


#bin_PROGRAMS = #gspawn-win32-helper
#gspawn_win32_helper_LDADD = #libglib-2.0.la
#gspawn_win32_helper_LDFLAGS = #-mwindows
mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_HEADER = ../config.h
CONFIG_CLEAN_FILES = 
LTLIBRARIES =  $(lib_LTLIBRARIES)


DEFS = -DHAVE_CONFIG_H -I. -I$(srcdir) -I..
CPPFLAGS = 
LDFLAGS = 
LIBS =  
libglib_2_0_la_OBJECTS =  garray.lo gasyncqueue.lo gbacktrace.lo \
gbsearcharray.lo gcache.lo gcompletion.lo gconvert.lo gdataset.lo \
gdate.lo gdir.lo gerror.lo gfileutils.lo ghash.lo ghook.lo \
giochannel.lo glist.lo gmain.lo gmarkup.lo gmem.lo gmessages.lo \
gnode.lo gpattern.lo gprimes.lo gqsort.lo gqueue.lo grel.lo grand.lo \
gscanner.lo gshell.lo gslist.lo gstrfuncs.lo gstring.lo gthread.lo \
gthreadpool.lo gtimer.lo gtree.lo guniprop.lo gutf8.lo gunibreak.lo \
gunicollate.lo gunidecomp.lo gutils.lo
#bin_PROGRAMS =  gspawn-win32-helper$(EXEEXT)
PROGRAMS =  $(bin_PROGRAMS)

gspawn_win32_helper_SOURCES = gspawn-win32-helper.c
gspawn_win32_helper_OBJECTS =  gspawn-win32-helper.$(OBJEXT)
#gspawn_win32_helper_DEPENDENCIES =  libglib-2.0.la
CFLAGS = -g -O2 -Wall -D_REENTRANT
COMPILE = $(CC) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) --mode=compile $(CC) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(LIBTOOL) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(LDFLAGS) -o $@
DATA =  $(noinst_DATA)

HEADERS =  $(glibinclude_HEADERS) $(glibsubinclude_HEADERS)

DIST_COMMON =  Makefile.am Makefile.in


DISTFILES = $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST)

TAR = gtar
GZIP_ENV = --best
SOURCES = $(libglib_2_0_la_SOURCES) $(EXTRA_libglib_2_0_la_SOURCES) gspawn-win32-helper.c
OBJECTS = $(libglib_2_0_la_OBJECTS) gspawn-win32-helper.$(OBJEXT)

all: all-redirect
.SUFFIXES:
.SUFFIXES: .S .c .lo .o .obj .s
$(srcdir)/Makefile.in: # Makefile.am $(top_srcdir)/configure.in $(ACLOCAL_M4) 
	cd $(top_srcdir) && $(AUTOMAKE) --gnu --include-deps glib/Makefile

Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status
	cd $(top_builddir) \
	  && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status


mostlyclean-libLTLIBRARIES:

clean-libLTLIBRARIES:
	-test -z "$(lib_LTLIBRARIES)" || rm -f $(lib_LTLIBRARIES)

distclean-libLTLIBRARIES:

maintainer-clean-libLTLIBRARIES:

install-libLTLIBRARIES: $(lib_LTLIBRARIES)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(libdir)
	@list='$(lib_LTLIBRARIES)'; for p in $$list; do \
	  if test -f $$p; then \
	    echo "$(LIBTOOL)  --mode=install $(INSTALL) $$p $(DESTDIR)$(libdir)/$$p"; \
	    $(LIBTOOL)  --mode=install $(INSTALL) $$p $(DESTDIR)$(libdir)/$$p; \
	  else :; fi; \
	done

uninstall-libLTLIBRARIES:
	@$(NORMAL_UNINSTALL)
	list='$(lib_LTLIBRARIES)'; for p in $$list; do \
	  $(LIBTOOL)  --mode=uninstall rm -f $(DESTDIR)$(libdir)/$$p; \
	done

.c.o:
	$(COMPILE) -c $<

# FIXME: We should only use cygpath when building on Windows,
# and only if it is available.
.c.obj:
	$(COMPILE) -c `cygpath -w $<`

.s.o:
	$(COMPILE) -c $<

.S.o:
	$(COMPILE) -c $<

mostlyclean-compile:
	-rm -f *.o core *.core
	-rm -f *.$(OBJEXT)

clean-compile:

distclean-compile:
	-rm -f *.tab.c

maintainer-clean-compile:

.c.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

.s.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

.S.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:

maintainer-clean-libtool:

libglib-2.0.la: $(libglib_2_0_la_OBJECTS) $(libglib_2_0_la_DEPENDENCIES)
	$(LINK) -rpath $(libdir) $(libglib_2_0_la_LDFLAGS) $(libglib_2_0_la_OBJECTS) $(libglib_2_0_la_LIBADD) $(LIBS)

mostlyclean-binPROGRAMS:

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)

distclean-binPROGRAMS:

maintainer-clean-binPROGRAMS:

install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(bindir)
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  if test -f $$p; then \
	    echo " $(LIBTOOL)  --mode=install $(INSTALL_PROGRAM) $$p $(DESTDIR)$(bindir)/`echo $$p|sed 's/$(EXEEXT)$$//'|sed '$(transform)'|sed 's/$$/$(EXEEXT)/'`"; \
	    $(LIBTOOL)  --mode=install $(INSTALL_PROGRAM) $$p $(DESTDIR)$(bindir)/`echo $$p|sed 's/$(EXEEXT)$$//'|sed '$(transform)'|sed 's/$$/$(EXEEXT)/'`; \
	  else :; fi; \
	done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	list='$(bin_PROGRAMS)'; for p in $$list; do \
	  rm -f $(DESTDIR)$(bindir)/`echo $$p|sed 's/$(EXEEXT)$$//'|sed '$(transform)'|sed 's/$$/$(EXEEXT)/'`; \
	done

gspawn-win32-helper$(EXEEXT): $(gspawn_win32_helper_OBJECTS) $(gspawn_win32_helper_DEPENDENCIES)
	@rm -f gspawn-win32-helper$(EXEEXT)
	$(LINK) $(gspawn_win32_helper_LDFLAGS) $(gspawn_win32_helper_OBJECTS) $(gspawn_win32_helper_LDADD) $(LIBS)

install-glibincludeHEADERS: $(glibinclude_HEADERS)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(glibincludedir)
	@list='$(glibinclude_HEADERS)'; for p in $$list; do \
	  if test -f "$$p"; then d= ; else d="$(srcdir)/"; fi; \
	  echo " $(INSTALL_DATA) $$d$$p $(DESTDIR)$(glibincludedir)/$$p"; \
	  $(INSTALL_DATA) $$d$$p $(DESTDIR)$(glibincludedir)/$$p; \
	done

uninstall-glibincludeHEADERS:
	@$(NORMAL_UNINSTALL)
	list='$(glibinclude_HEADERS)'; for p in $$list; do \
	  rm -f $(DESTDIR)$(glibincludedir)/$$p; \
	done

install-glibsubincludeHEADERS: $(glibsubinclude_HEADERS)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(glibsubincludedir)
	@list='$(glibsubinclude_HEADERS)'; for p in $$list; do \
	  if test -f "$$p"; then d= ; else d="$(srcdir)/"; fi; \
	  echo " $(INSTALL_DATA) $$d$$p $(DESTDIR)$(glibsubincludedir)/$$p"; \
	  $(INSTALL_DATA) $$d$$p $(DESTDIR)$(glibsubincludedir)/$$p; \
	done

uninstall-glibsubincludeHEADERS:
	@$(NORMAL_UNINSTALL)
	list='$(glibsubinclude_HEADERS)'; for p in $$list; do \
	  rm -f $(DESTDIR)$(glibsubincludedir)/$$p; \
	done

# This directory's subdirectories are mostly independent; you can cd
# into them and run `make' without going through this Makefile.
# To change the values of `make' variables: instead of editing Makefiles,
# (1) if the variable is set in `config.status', edit `config.status'
#     (which will cause the Makefiles to be regenerated when you run `make');
# (2) otherwise, pass the desired values on the `make' command line.



all-recursive install-data-recursive install-exec-recursive \
installdirs-recursive install-recursive uninstall-recursive  \
check-recursive installcheck-recursive info-recursive dvi-recursive:
	@set fnord $(MAKEFLAGS); amf=$$2; \
	dot_seen=no; \
	target=`echo $@ | sed s/-recursive//`; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    dot_seen=yes; \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	   || case "$$amf" in *=*) exit 1;; *k*) fail=yes;; *) exit 1;; esac; \
	done; \
	if test "$$dot_seen" = "no"; then \
	  $(MAKE) $(AM_MAKEFLAGS) "$$target-am" || exit 1; \
	fi; test -z "$$fail"

mostlyclean-recursive clean-recursive distclean-recursive \
maintainer-clean-recursive:
	@set fnord $(MAKEFLAGS); amf=$$2; \
	dot_seen=no; \
	rev=''; list='$(SUBDIRS)'; for subdir in $$list; do \
	  rev="$$subdir $$rev"; \
	  test "$$subdir" != "." || dot_seen=yes; \
	done; \
	test "$$dot_seen" = "no" && rev=". $$rev"; \
	target=`echo $@ | sed s/-recursive//`; \
	for subdir in $$rev; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	   || case "$$amf" in *=*) exit 1;; *k*) fail=yes;; *) exit 1;; esac; \
	done && test -z "$$fail"
tags-recursive:
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  test "$$subdir" = . || (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) tags); \
	done

tags: TAGS

ID: $(HEADERS) $(SOURCES) $(LISP)
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	here=`pwd` && cd $(srcdir) \
	  && mkid -f$$here/ID $$unique $(LISP)

TAGS: tags-recursive $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
   if test "$$subdir" = .; then :; else \
	    test -f $$subdir/TAGS && tags="$$tags -i $$here/$$subdir/TAGS"; \
   fi; \
	done; \
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(ETAGS_ARGS)$$unique$(LISP)$$tags" \
	  || (cd $(srcdir) && etags $(ETAGS_ARGS) $$tags  $$unique $(LISP) -o $$here/TAGS)

mostlyclean-tags:

clean-tags:

distclean-tags:
	-rm -f TAGS ID

maintainer-clean-tags:

distdir = $(top_builddir)/$(PACKAGE)-$(VERSION)/$(subdir)

subdir = glib

distdir: $(DISTFILES)
	@for file in $(DISTFILES); do \
	  d=$(srcdir); \
	  if test -d $$d/$$file; then \
	    cp -pr $$d/$$file $(distdir)/$$file; \
	  else \
	    test -f $(distdir)/$$file \
	    || ln $$d/$$file $(distdir)/$$file 2> /dev/null \
	    || cp -p $$d/$$file $(distdir)/$$file || :; \
	  fi; \
	done
	for subdir in $(SUBDIRS); do \
	  if test "$$subdir" = .; then :; else \
	    test -d $(distdir)/$$subdir \
	    || mkdir $(distdir)/$$subdir \
	    || exit 1; \
	    chmod 777 $(distdir)/$$subdir; \
	    (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) top_distdir=../$(top_distdir) distdir=../$(distdir)/$$subdir distdir) \
	      || exit 1; \
	  fi; \
	done
	$(MAKE) $(AM_MAKEFLAGS) top_distdir="$(top_distdir)" distdir="$(distdir)" dist-hook
garray.lo garray.o : garray.c ../config.h glib.h galloca.h gtypes.h \
	../glibconfig.h gmacros.h garray.h gasyncqueue.h gthread.h \
	gerror.h gquark.h gbacktrace.h gcache.h glist.h gmem.h \
	gcompletion.h gconvert.h gdataset.h gdate.h gdir.h gfileutils.h \
	ghash.h ghook.h giochannel.h gmain.h gslist.h gstring.h \
	gunicode.h gmarkup.h gmessages.h gnode.h gpattern.h gprimes.h \
	gqsort.h gqueue.h grand.h grel.h gscanner.h gshell.h gspawn.h \
	gstrfuncs.h gthreadpool.h gtimer.h gtree.h gutils.h
gasyncqueue.lo gasyncqueue.o : gasyncqueue.c glib.h galloca.h gtypes.h \
	../glibconfig.h gmacros.h garray.h gasyncqueue.h gthread.h \
	gerror.h gquark.h gbacktrace.h gcache.h glist.h gmem.h \
	gcompletion.h gconvert.h gdataset.h gdate.h gdir.h gfileutils.h \
	ghash.h ghook.h giochannel.h gmain.h gslist.h gstring.h \
	gunicode.h gmarkup.h gmessages.h gnode.h gpattern.h gprimes.h \
	gqsort.h gqueue.h grand.h grel.h gscanner.h gshell.h gspawn.h \
	gstrfuncs.h gthreadpool.h gtimer.h gtree.h gutils.h
gbacktrace.lo gbacktrace.o : gbacktrace.c ../config.h glib.h galloca.h \
	gtypes.h ../glibconfig.h gmacros.h garray.h gasyncqueue.h \
	gthread.h gerror.h gquark.h gbacktrace.h gcache.h glist.h \
	gmem.h gcompletion.h gconvert.h gdataset.h gdate.h gdir.h \
	gfileutils.h ghash.h ghook.h giochannel.h gmain.h gslist.h \
	gstring.h gunicode.h gmarkup.h gmessages.h gnode.h gpattern.h \
	gprimes.h gqsort.h gqueue.h grand.h grel.h gscanner.h gshell.h \
	gspawn.h gstrfuncs.h gthreadpool.h gtimer.h gtree.h gutils.h
gbsearcharray.lo gbsearcharray.o : gbsearcharray.c ../config.h \
	gbsearcharray.h gtypes.h ../glibconfig.h gmacros.h gutils.h \
	gmem.h gmessages.h
gcache.lo gcache.o : gcache.c glib.h galloca.h gtypes.h ../glibconfig.h \
	gmacros.h garray.h gasyncqueue.h gthread.h gerror.h gquark.h \
	gbacktrace.h gcache.h glist.h gmem.h gcompletion.h gconvert.h \
	gdataset.h gdate.h gdir.h gfileutils.h ghash.h ghook.h \
	giochannel.h gmain.h gslist.h gstring.h gunicode.h gmarkup.h \
	gmessages.h gnode.h gpattern.h gprimes.h gqsort.h gqueue.h \
	grand.h grel.h gscanner.h gshell.h gspawn.h gstrfuncs.h \
	gthreadpool.h gtimer.h gtree.h gutils.h
gcompletion.lo gcompletion.o : gcompletion.c glib.h galloca.h gtypes.h \
	../glibconfig.h gmacros.h garray.h gasyncqueue.h gthread.h \
	gerror.h gquark.h gbacktrace.h gcache.h glist.h gmem.h \
	gcompletion.h gconvert.h gdataset.h gdate.h gdir.h gfileutils.h \
	ghash.h ghook.h giochannel.h gmain.h gslist.h gstring.h \
	gunicode.h gmarkup.h gmessages.h gnode.h gpattern.h gprimes.h \
	gqsort.h gqueue.h grand.h grel.h gscanner.h gshell.h gspawn.h \
	gstrfuncs.h gthreadpool.h gtimer.h gtree.h gutils.h
gconvert.lo gconvert.o : gconvert.c ../config.h glib.h galloca.h \
	gtypes.h ../glibconfig.h gmacros.h garray.h gasyncqueue.h \
	gthread.h gerror.h gquark.h gbacktrace.h gcache.h glist.h \
	gmem.h gcompletion.h gconvert.h gdataset.h gdate.h gdir.h \
	gfileutils.h ghash.h ghook.h giochannel.h gmain.h gslist.h \
	gstring.h gunicode.h gmarkup.h gmessages.h gnode.h gpattern.h \
	gprimes.h gqsort.h gqueue.h grand.h grel.h gscanner.h gshell.h \
	gspawn.h gstrfuncs.h gthreadpool.h gtimer.h gtree.h gutils.h \
	glibintl.h
gdataset.lo gdataset.o : gdataset.c glib.h galloca.h gtypes.h \
	../glibconfig.h gmacros.h garray.h gasyncqueue.h gthread.h \
	gerror.h gquark.h gbacktrace.h gcache.h glist.h gmem.h \
	gcompletion.h gconvert.h gdataset.h gdate.h gdir.h gfileutils.h \
	ghash.h ghook.h giochannel.h gmain.h gslist.h gstring.h \
	gunicode.h gmarkup.h gmessages.h gnode.h gpattern.h gprimes.h \
	gqsort.h gqueue.h grand.h grel.h gscanner.h gshell.h gspawn.h \
	gstrfuncs.h gthreadpool.h gtimer.h gtree.h gutils.h
gdate.lo gdate.o : gdate.c ../config.h glib.h galloca.h gtypes.h \
	../glibconfig.h gmacros.h garray.h gasyncqueue.h gthread.h \
	gerror.h gquark.h gbacktrace.h gcache.h glist.h gmem.h \
	gcompletion.h gconvert.h gdataset.h gdate.h gdir.h gfileutils.h \
	ghash.h ghook.h giochannel.h gmain.h gslist.h gstring.h \
	gunicode.h gmarkup.h gmessages.h gnode.h gpattern.h gprimes.h \
	gqsort.h gqueue.h grand.h grel.h gscanner.h gshell.h gspawn.h \
	gstrfuncs.h gthreadpool.h gtimer.h gtree.h gutils.h
gdir.lo gdir.o : gdir.c ../config.h glib.h galloca.h gtypes.h \
	../glibconfig.h gmacros.h garray.h gasyncqueue.h gthread.h \
	gerror.h gquark.h gbacktrace.h gcache.h glist.h gmem.h \
	gcompletion.h gconvert.h gdataset.h gdate.h gdir.h gfileutils.h \
	ghash.h ghook.h giochannel.h gmain.h gslist.h gstring.h \
	gunicode.h gmarkup.h gmessages.h gnode.h gpattern.h gprimes.h \
	gqsort.h gqueue.h grand.h grel.h gscanner.h gshell.h gspawn.h \
	gstrfuncs.h gthreadpool.h gtimer.h gtree.h gutils.h gdir.h \
	glibintl.h
gerror.lo gerror.o : gerror.c glib.h galloca.h gtypes.h ../glibconfig.h \
	gmacros.h garray.h gasyncqueue.h gthread.h gerror.h gquark.h \
	gbacktrace.h gcache.h glist.h gmem.h gcompletion.h gconvert.h \
	gdataset.h gdate.h gdir.h gfileutils.h ghash.h ghook.h \
	giochannel.h gmain.h gslist.h gstring.h gunicode.h gmarkup.h \
	gmessages.h gnode.h gpattern.h gprimes.h gqsort.h gqueue.h \
	grand.h grel.h gscanner.h gshell.h gspawn.h gstrfuncs.h \
	gthreadpool.h gtimer.h gtree.h gutils.h
gfileutils.lo gfileutils.o : gfileutils.c ../config.h glib.h galloca.h \
	gtypes.h ../glibconfig.h gmacros.h garray.h gasyncqueue.h \
	gthread.h gerror.h gquark.h gbacktrace.h gcache.h glist.h \
	gmem.h gcompletion.h gconvert.h gdataset.h gdate.h gdir.h \
	gfileutils.h ghash.h ghook.h giochannel.h gmain.h gslist.h \
	gstring.h gunicode.h gmarkup.h gmessages.h gnode.h gpattern.h \
	gprimes.h gqsort.h gqueue.h grand.h grel.h gscanner.h gshell.h \
	gspawn.h gstrfuncs.h gthreadpool.h gtimer.h gtree.h gutils.h \
	glibintl.h
ghash.lo ghash.o : ghash.c ../config.h glib.h galloca.h gtypes.h \
	../glibconfig.h gmacros.h garray.h gasyncqueue.h gthread.h \
	gerror.h gquark.h gbacktrace.h gcache.h glist.h gmem.h \
	gcompletion.h gconvert.h gdataset.h gdate.h gdir.h gfileutils.h \
	ghash.h ghook.h giochannel.h gmain.h gslist.h gstring.h \
	gunicode.h gmarkup.h gmessages.h gnode.h gpattern.h gprimes.h \
	gqsort.h gqueue.h grand.h grel.h gscanner.h gshell.h gspawn.h \
	gstrfuncs.h gthreadpool.h gtimer.h gtree.h gutils.h
ghook.lo ghook.o : ghook.c glib.h galloca.h gtypes.h ../glibconfig.h \
	gmacros.h garray.h gasyncqueue.h gthread.h gerror.h gquark.h \
	gbacktrace.h gcache.h glist.h gmem.h gcompletion.h gconvert.h \
	gdataset.h gdate.h gdir.h gfileutils.h ghash.h ghook.h \
	giochannel.h gmain.h gslist.h gstring.h gunicode.h gmarkup.h \
	gmessages.h gnode.h gpattern.h gprimes.h gqsort.h gqueue.h \
	grand.h grel.h gscanner.h gshell.h gspawn.h gstrfuncs.h \
	gthreadpool.h gtimer.h gtree.h gutils.h
giochannel.lo giochannel.o : giochannel.c ../config.h giochannel.h \
	gconvert.h gerror.h gquark.h gtypes.h ../glibconfig.h gmacros.h \
	gmain.h gslist.h gmem.h gthread.h gstring.h gunicode.h glib.h \
	galloca.h garray.h gasyncqueue.h gbacktrace.h gcache.h glist.h \
	gcompletion.h gdataset.h gdate.h gdir.h gfileutils.h ghash.h \
	ghook.h giochannel.h gmarkup.h gmessages.h gnode.h gpattern.h \
	gprimes.h gqsort.h gqueue.h grand.h grel.h gscanner.h gshell.h \
	gspawn.h gstrfuncs.h gthreadpool.h gtimer.h gtree.h gutils.h \
	glibintl.h
giounix.lo giounix.o : giounix.c ../config.h glib.h galloca.h gtypes.h \
	../glibconfig.h gmacros.h garray.h gasyncqueue.h gthread.h \
	gerror.h gquark.h gbacktrace.h gcache.h glist.h gmem.h \
	gcompletion.h gconvert.h gdataset.h gdate.h gdir.h gfileutils.h \
	ghash.h ghook.h giochannel.h gmain.h gslist.h gstring.h \
	gunicode.h gmarkup.h gmessages.h gnode.h gpattern.h gprimes.h \
	gqsort.h gqueue.h grand.h grel.h gscanner.h gshell.h gspawn.h \
	gstrfuncs.h gthreadpool.h gtimer.h gtree.h gutils.h
glist.lo glist.o : glist.c ../config.h glib.h galloca.h gtypes.h \
	../glibconfig.h gmacros.h garray.h gasyncqueue.h gthread.h \
	gerror.h gquark.h gbacktrace.h gcache.h glist.h gmem.h \
	gcompletion.h gconvert.h gdataset.h gdate.h gdir.h gfileutils.h \
	ghash.h ghook.h giochannel.h gmain.h gslist.h gstring.h \
	gunicode.h gmarkup.h gmessages.h gnode.h gpattern.h gprimes.h \
	gqsort.h gqueue.h grand.h grel.h gscanner.h gshell.h gspawn.h \
	gstrfuncs.h gthreadpool.h gtimer.h gtree.h gutils.h
gmain.lo gmain.o : gmain.c ../config.h glib.h galloca.h gtypes.h \
	../glibconfig.h gmacros.h garray.h gasyncqueue.h gthread.h \
	gerror.h gquark.h gbacktrace.h gcache.h glist.h gmem.h \
	gcompletion.h gconvert.h gdataset.h gdate.h gdir.h gfileutils.h \
	ghash.h ghook.h giochannel.h gmain.h gslist.h gstring.h \
	gunicode.h gmarkup.h gmessages.h gnode.h gpattern.h gprimes.h \
	gqsort.h gqueue.h grand.h grel.h gscanner.h gshell.h gspawn.h \
	gstrfuncs.h gthreadpool.h gtimer.h gtree.h gutils.h
gmarkup.lo gmarkup.o : gmarkup.c ../config.h glib.h galloca.h gtypes.h \
	../glibconfig.h gmacros.h garray.h gasyncqueue.h gthread.h \
	gerror.h gquark.h gbacktrace.h gcache.h glist.h gmem.h \
	gcompletion.h gconvert.h gdataset.h gdate.h gdir.h gfileutils.h \
	ghash.h ghook.h giochannel.h gmain.h gslist.h gstring.h \
	gunicode.h gmarkup.h gmessages.h gnode.h gpattern.h gprimes.h \
	gqsort.h gqueue.h grand.h grel.h gscanner.h gshell.h gspawn.h \
	gstrfuncs.h gthreadpool.h gtimer.h gtree.h gutils.h glibintl.h
gmem.lo gmem.o : gmem.c ../config.h glib.h galloca.h gtypes.h \
	../glibconfig.h gmacros.h garray.h gasyncqueue.h gthread.h \
	gerror.h gquark.h gbacktrace.h gcache.h glist.h gmem.h \
	gcompletion.h gconvert.h gdataset.h gdate.h gdir.h gfileutils.h \
	ghash.h ghook.h giochannel.h gmain.h gslist.h gstring.h \
	gunicode.h gmarkup.h gmessages.h gnode.h gpattern.h gprimes.h \
	gqsort.h gqueue.h grand.h grel.h gscanner.h gshell.h gspawn.h \
	gstrfuncs.h gthreadpool.h gtimer.h gtree.h gutils.h
gmessages.lo gmessages.o : gmessages.c ../config.h glib.h galloca.h \
	gtypes.h ../glibconfig.h gmacros.h garray.h gasyncqueue.h \
	gthread.h gerror.h gquark.h gbacktrace.h gcache.h glist.h \
	gmem.h gcompletion.h gconvert.h gdataset.h gdate.h gdir.h \
	gfileutils.h ghash.h ghook.h giochannel.h gmain.h gslist.h \
	gstring.h gunicode.h gmarkup.h gmessages.h gnode.h gpattern.h \
	gprimes.h gqsort.h gqueue.h grand.h grel.h gscanner.h gshell.h \
	gspawn.h gstrfuncs.h gthreadpool.h gtimer.h gtree.h gutils.h \
	gdebug.h
gnode.lo gnode.o : gnode.c ../config.h glib.h galloca.h gtypes.h \
	../glibconfig.h gmacros.h garray.h gasyncqueue.h gthread.h \
	gerror.h gquark.h gbacktrace.h gcache.h glist.h gmem.h \
	gcompletion.h gconvert.h gdataset.h gdate.h gdir.h gfileutils.h \
	ghash.h ghook.h giochannel.h gmain.h gslist.h gstring.h \
	gunicode.h gmarkup.h gmessages.h gnode.h gpattern.h gprimes.h \
	gqsort.h gqueue.h grand.h grel.h gscanner.h gshell.h gspawn.h \
	gstrfuncs.h gthreadpool.h gtimer.h gtree.h gutils.h
gpattern.lo gpattern.o : gpattern.c gpattern.h gtypes.h ../glibconfig.h \
	gmacros.h gmacros.h gmessages.h gmem.h gunicode.h gerror.h \
	gquark.h gutils.h
gprimes.lo gprimes.o : gprimes.c glib.h galloca.h gtypes.h \
	../glibconfig.h gmacros.h garray.h gasyncqueue.h gthread.h \
	gerror.h gquark.h gbacktrace.h gcache.h glist.h gmem.h \
	gcompletion.h gconvert.h gdataset.h gdate.h gdir.h gfileutils.h \
	ghash.h ghook.h giochannel.h gmain.h gslist.h gstring.h \
	gunicode.h gmarkup.h gmessages.h gnode.h gpattern.h gprimes.h \
	gqsort.h gqueue.h grand.h grel.h gscanner.h gshell.h gspawn.h \
	gstrfuncs.h gthreadpool.h gtimer.h gtree.h gutils.h
gqsort.lo gqsort.o : gqsort.c glib.h galloca.h gtypes.h ../glibconfig.h \
	gmacros.h garray.h gasyncqueue.h gthread.h gerror.h gquark.h \
	gbacktrace.h gcache.h glist.h gmem.h gcompletion.h gconvert.h \
	gdataset.h gdate.h gdir.h gfileutils.h ghash.h ghook.h \
	giochannel.h gmain.h gslist.h gstring.h gunicode.h gmarkup.h \
	gmessages.h gnode.h gpattern.h gprimes.h gqsort.h gqueue.h \
	grand.h grel.h gscanner.h gshell.h gspawn.h gstrfuncs.h \
	gthreadpool.h gtimer.h gtree.h gutils.h
gqueue.lo gqueue.o : gqueue.c ../config.h glib.h galloca.h gtypes.h \
	../glibconfig.h gmacros.h garray.h gasyncqueue.h gthread.h \
	gerror.h gquark.h gbacktrace.h gcache.h glist.h gmem.h \
	gcompletion.h gconvert.h gdataset.h gdate.h gdir.h gfileutils.h \
	ghash.h ghook.h giochannel.h gmain.h gslist.h gstring.h \
	gunicode.h gmarkup.h gmessages.h gnode.h gpattern.h gprimes.h \
	gqsort.h gqueue.h grand.h grel.h gscanner.h gshell.h gspawn.h \
	gstrfuncs.h gthreadpool.h gtimer.h gtree.h gutils.h
grand.lo grand.o : grand.c glib.h galloca.h gtypes.h ../glibconfig.h \
	gmacros.h garray.h gasyncqueue.h gthread.h gerror.h gquark.h \
	gbacktrace.h gcache.h glist.h gmem.h gcompletion.h gconvert.h \
	gdataset.h gdate.h gdir.h gfileutils.h ghash.h ghook.h \
	giochannel.h gmain.h gslist.h gstring.h gunicode.h gmarkup.h \
	gmessages.h gnode.h gpattern.h gprimes.h gqsort.h gqueue.h \
	grand.h grel.h gscanner.h gshell.h gspawn.h gstrfuncs.h \
	gthreadpool.h gtimer.h gtree.h gutils.h
grel.lo grel.o : grel.c glib.h galloca.h gtypes.h ../glibconfig.h \
	gmacros.h garray.h gasyncqueue.h gthread.h gerror.h gquark.h \
	gbacktrace.h gcache.h glist.h gmem.h gcompletion.h gconvert.h \
	gdataset.h gdate.h gdir.h gfileutils.h ghash.h ghook.h \
	giochannel.h gmain.h gslist.h gstring.h gunicode.h gmarkup.h \
	gmessages.h gnode.h gpattern.h gprimes.h gqsort.h gqueue.h \
	grand.h grel.h gscanner.h gshell.h gspawn.h gstrfuncs.h \
	gthreadpool.h gtimer.h gtree.h gutils.h
gscanner.lo gscanner.o : gscanner.c ../config.h glib.h galloca.h \
	gtypes.h ../glibconfig.h gmacros.h garray.h gasyncqueue.h \
	gthread.h gerror.h gquark.h gbacktrace.h gcache.h glist.h \
	gmem.h gcompletion.h gconvert.h gdataset.h gdate.h gdir.h \
	gfileutils.h ghash.h ghook.h giochannel.h gmain.h gslist.h \
	gstring.h gunicode.h gmarkup.h gmessages.h gnode.h gpattern.h \
	gprimes.h gqsort.h gqueue.h grand.h grel.h gscanner.h gshell.h \
	gspawn.h gstrfuncs.h gthreadpool.h gtimer.h gtree.h gutils.h
gshell.lo gshell.o : gshell.c ../config.h glib.h galloca.h gtypes.h \
	../glibconfig.h gmacros.h garray.h gasyncqueue.h gthread.h \
	gerror.h gquark.h gbacktrace.h gcache.h glist.h gmem.h \
	gcompletion.h gconvert.h gdataset.h gdate.h gdir.h gfileutils.h \
	ghash.h ghook.h giochannel.h gmain.h gslist.h gstring.h \
	gunicode.h gmarkup.h gmessages.h gnode.h gpattern.h gprimes.h \
	gqsort.h gqueue.h grand.h grel.h gscanner.h gshell.h gspawn.h \
	gstrfuncs.h gthreadpool.h gtimer.h gtree.h gutils.h glibintl.h
gslist.lo gslist.o : gslist.c ../config.h glib.h galloca.h gtypes.h \
	../glibconfig.h gmacros.h garray.h gasyncqueue.h gthread.h \
	gerror.h gquark.h gbacktrace.h gcache.h glist.h gmem.h \
	gcompletion.h gconvert.h gdataset.h gdate.h gdir.h gfileutils.h \
	ghash.h ghook.h giochannel.h gmain.h gslist.h gstring.h \
	gunicode.h gmarkup.h gmessages.h gnode.h gpattern.h gprimes.h \
	gqsort.h gqueue.h grand.h grel.h gscanner.h gshell.h gspawn.h \
	gstrfuncs.h gthreadpool.h gtimer.h gtree.h gutils.h
gspawn.lo gspawn.o : gspawn.c ../config.h glib.h galloca.h gtypes.h \
	../glibconfig.h gmacros.h garray.h gasyncqueue.h gthread.h \
	gerror.h gquark.h gbacktrace.h gcache.h glist.h gmem.h \
	gcompletion.h gconvert.h gdataset.h gdate.h gdir.h gfileutils.h \
	ghash.h ghook.h giochannel.h gmain.h gslist.h gstring.h \
	gunicode.h gmarkup.h gmessages.h gnode.h gpattern.h gprimes.h \
	gqsort.h gqueue.h grand.h grel.h gscanner.h gshell.h gspawn.h \
	gstrfuncs.h gthreadpool.h gtimer.h gtree.h gutils.h glibintl.h
gstrfuncs.lo gstrfuncs.o : gstrfuncs.c ../config.h glib.h galloca.h \
	gtypes.h ../glibconfig.h gmacros.h garray.h gasyncqueue.h \
	gthread.h gerror.h gquark.h gbacktrace.h gcache.h glist.h \
	gmem.h gcompletion.h gconvert.h gdataset.h gdate.h gdir.h \
	gfileutils.h ghash.h ghook.h giochannel.h gmain.h gslist.h \
	gstring.h gunicode.h gmarkup.h gmessages.h gnode.h gpattern.h \
	gprimes.h gqsort.h gqueue.h grand.h grel.h gscanner.h gshell.h \
	gspawn.h gstrfuncs.h gthreadpool.h gtimer.h gtree.h gutils.h
gstring.lo gstring.o : gstring.c ../config.h glib.h galloca.h gtypes.h \
	../glibconfig.h gmacros.h garray.h gasyncqueue.h gthread.h \
	gerror.h gquark.h gbacktrace.h gcache.h glist.h gmem.h \
	gcompletion.h gconvert.h gdataset.h gdate.h gdir.h gfileutils.h \
	ghash.h ghook.h giochannel.h gmain.h gslist.h gstring.h \
	gunicode.h gmarkup.h gmessages.h gnode.h gpattern.h gprimes.h \
	gqsort.h gqueue.h grand.h grel.h gscanner.h gshell.h gspawn.h \
	gstrfuncs.h gthreadpool.h gtimer.h gtree.h gutils.h
gthread.lo gthread.o : gthread.c ../config.h glib.h galloca.h gtypes.h \
	../glibconfig.h gmacros.h garray.h gasyncqueue.h gthread.h \
	gerror.h gquark.h gbacktrace.h gcache.h glist.h gmem.h \
	gcompletion.h gconvert.h gdataset.h gdate.h gdir.h gfileutils.h \
	ghash.h ghook.h giochannel.h gmain.h gslist.h gstring.h \
	gunicode.h gmarkup.h gmessages.h gnode.h gpattern.h gprimes.h \
	gqsort.h gqueue.h grand.h grel.h gscanner.h gshell.h gspawn.h \
	gstrfuncs.h gthreadpool.h gtimer.h gtree.h gutils.h
gthreadpool.lo gthreadpool.o : gthreadpool.c glib.h galloca.h gtypes.h \
	../glibconfig.h gmacros.h garray.h gasyncqueue.h gthread.h \
	gerror.h gquark.h gbacktrace.h gcache.h glist.h gmem.h \
	gcompletion.h gconvert.h gdataset.h gdate.h gdir.h gfileutils.h \
	ghash.h ghook.h giochannel.h gmain.h gslist.h gstring.h \
	gunicode.h gmarkup.h gmessages.h gnode.h gpattern.h gprimes.h \
	gqsort.h gqueue.h grand.h grel.h gscanner.h gshell.h gspawn.h \
	gstrfuncs.h gthreadpool.h gtimer.h gtree.h gutils.h
gtimer.lo gtimer.o : gtimer.c ../config.h glib.h galloca.h gtypes.h \
	../glibconfig.h gmacros.h garray.h gasyncqueue.h gthread.h \
	gerror.h gquark.h gbacktrace.h gcache.h glist.h gmem.h \
	gcompletion.h gconvert.h gdataset.h gdate.h gdir.h gfileutils.h \
	ghash.h ghook.h giochannel.h gmain.h gslist.h gstring.h \
	gunicode.h gmarkup.h gmessages.h gnode.h gpattern.h gprimes.h \
	gqsort.h gqueue.h grand.h grel.h gscanner.h gshell.h gspawn.h \
	gstrfuncs.h gthreadpool.h gtimer.h gtree.h gutils.h
gtree.lo gtree.o : gtree.c ../config.h glib.h galloca.h gtypes.h \
	../glibconfig.h gmacros.h garray.h gasyncqueue.h gthread.h \
	gerror.h gquark.h gbacktrace.h gcache.h glist.h gmem.h \
	gcompletion.h gconvert.h gdataset.h gdate.h gdir.h gfileutils.h \
	ghash.h ghook.h giochannel.h gmain.h gslist.h gstring.h \
	gunicode.h gmarkup.h gmessages.h gnode.h gpattern.h gprimes.h \
	gqsort.h gqueue.h grand.h grel.h gscanner.h gshell.h gspawn.h \
	gstrfuncs.h gthreadpool.h gtimer.h gtree.h gutils.h
gunibreak.lo gunibreak.o : gunibreak.c ../config.h glib.h galloca.h \
	gtypes.h ../glibconfig.h gmacros.h garray.h gasyncqueue.h \
	gthread.h gerror.h gquark.h gbacktrace.h gcache.h glist.h \
	gmem.h gcompletion.h gconvert.h gdataset.h gdate.h gdir.h \
	gfileutils.h ghash.h ghook.h giochannel.h gmain.h gslist.h \
	gstring.h gunicode.h gmarkup.h gmessages.h gnode.h gpattern.h \
	gprimes.h gqsort.h gqueue.h grand.h grel.h gscanner.h gshell.h \
	gspawn.h gstrfuncs.h gthreadpool.h gtimer.h gtree.h gutils.h \
	gunibreak.h
gunicollate.lo gunicollate.o : gunicollate.c glib.h galloca.h gtypes.h \
	../glibconfig.h gmacros.h garray.h gasyncqueue.h gthread.h \
	gerror.h gquark.h gbacktrace.h gcache.h glist.h gmem.h \
	gcompletion.h gconvert.h gdataset.h gdate.h gdir.h gfileutils.h \
	ghash.h ghook.h giochannel.h gmain.h gslist.h gstring.h \
	gunicode.h gmarkup.h gmessages.h gnode.h gpattern.h gprimes.h \
	gqsort.h gqueue.h grand.h grel.h gscanner.h gshell.h gspawn.h \
	gstrfuncs.h gthreadpool.h gtimer.h gtree.h gutils.h
gunidecomp.lo gunidecomp.o : gunidecomp.c ../config.h glib.h galloca.h \
	gtypes.h ../glibconfig.h gmacros.h garray.h gasyncqueue.h \
	gthread.h gerror.h gquark.h gbacktrace.h gcache.h glist.h \
	gmem.h gcompletion.h gconvert.h gdataset.h gdate.h gdir.h \
	gfileutils.h ghash.h ghook.h giochannel.h gmain.h gslist.h \
	gstring.h gunicode.h gmarkup.h gmessages.h gnode.h gpattern.h \
	gprimes.h gqsort.h gqueue.h grand.h grel.h gscanner.h gshell.h \
	gspawn.h gstrfuncs.h gthreadpool.h gtimer.h gtree.h gutils.h \
	gunidecomp.h gunicomp.h
guniprop.lo guniprop.o : guniprop.c ../config.h glib.h galloca.h \
	gtypes.h ../glibconfig.h gmacros.h garray.h gasyncqueue.h \
	gthread.h gerror.h gquark.h gbacktrace.h gcache.h glist.h \
	gmem.h gcompletion.h gconvert.h gdataset.h gdate.h gdir.h \
	gfileutils.h ghash.h ghook.h giochannel.h gmain.h gslist.h \
	gstring.h gunicode.h gmarkup.h gmessages.h gnode.h gpattern.h \
	gprimes.h gqsort.h gqueue.h grand.h grel.h gscanner.h gshell.h \
	gspawn.h gstrfuncs.h gthreadpool.h gtimer.h gtree.h gutils.h \
	gunichartables.h
gutf8.lo gutf8.o : gutf8.c ../config.h glib.h galloca.h gtypes.h \
	../glibconfig.h gmacros.h garray.h gasyncqueue.h gthread.h \
	gerror.h gquark.h gbacktrace.h gcache.h glist.h gmem.h \
	gcompletion.h gconvert.h gdataset.h gdate.h gdir.h gfileutils.h \
	ghash.h ghook.h giochannel.h gmain.h gslist.h gstring.h \
	gunicode.h gmarkup.h gmessages.h gnode.h gpattern.h gprimes.h \
	gqsort.h gqueue.h grand.h grel.h gscanner.h gshell.h gspawn.h \
	gstrfuncs.h gthreadpool.h gtimer.h gtree.h gutils.h \
	libcharset/libcharset.h glibintl.h
gutils.lo gutils.o : gutils.c ../config.h glib.h galloca.h gtypes.h \
	../glibconfig.h gmacros.h garray.h gasyncqueue.h gthread.h \
	gerror.h gquark.h gbacktrace.h gcache.h glist.h gmem.h \
	gcompletion.h gconvert.h gdataset.h gdate.h gdir.h gfileutils.h \
	ghash.h ghook.h giochannel.h gmain.h gslist.h gstring.h \
	gunicode.h gmarkup.h gmessages.h gnode.h gpattern.h gprimes.h \
	gqsort.h gqueue.h grand.h grel.h gscanner.h gshell.h gspawn.h \
	gstrfuncs.h gthreadpool.h gtimer.h gtree.h gutils.h

info-am:
info: info-recursive
dvi-am:
dvi: dvi-recursive
check-am: all-am
check: check-recursive
installcheck-am:
installcheck: installcheck-recursive
install-exec-am: install-libLTLIBRARIES install-binPROGRAMS
install-exec: install-exec-recursive

install-data-am: install-glibincludeHEADERS \
		install-glibsubincludeHEADERS install-data-local
install-data: install-data-recursive

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am
install: install-recursive
uninstall-am: uninstall-libLTLIBRARIES uninstall-binPROGRAMS \
		uninstall-glibincludeHEADERS \
		uninstall-glibsubincludeHEADERS uninstall-local
uninstall: uninstall-recursive
all-am: Makefile $(LTLIBRARIES) $(PROGRAMS) $(DATA) $(HEADERS)
all-redirect: all-recursive
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) AM_INSTALL_PROGRAM_FLAGS=-s install
installdirs: installdirs-recursive
installdirs-am:
	$(mkinstalldirs)  $(DESTDIR)$(libdir) $(DESTDIR)$(bindir) \
		$(DESTDIR)$(glibincludedir) \
		$(DESTDIR)$(glibsubincludedir)


mostlyclean-generic:

clean-generic:

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES)
	-rm -f config.cache config.log stamp-h stamp-h[0-9]*

maintainer-clean-generic:
mostlyclean-am:  mostlyclean-libLTLIBRARIES mostlyclean-compile \
		mostlyclean-libtool mostlyclean-binPROGRAMS \
		mostlyclean-tags mostlyclean-generic

mostlyclean: mostlyclean-recursive

clean-am:  clean-libLTLIBRARIES clean-compile clean-libtool \
		clean-binPROGRAMS clean-tags clean-generic \
		mostlyclean-am

clean: clean-recursive

distclean-am:  distclean-libLTLIBRARIES distclean-compile \
		distclean-libtool distclean-binPROGRAMS distclean-tags \
		distclean-generic clean-am
	-rm -f libtool

distclean: distclean-recursive

maintainer-clean-am:  maintainer-clean-libLTLIBRARIES \
		maintainer-clean-compile maintainer-clean-libtool \
		maintainer-clean-binPROGRAMS maintainer-clean-tags \
		maintainer-clean-generic distclean-am
	@echo "This command is intended for maintainers to use;"
	@echo "it deletes files that may require special tools to rebuild."

maintainer-clean: maintainer-clean-recursive

.PHONY: mostlyclean-libLTLIBRARIES distclean-libLTLIBRARIES \
clean-libLTLIBRARIES maintainer-clean-libLTLIBRARIES \
uninstall-libLTLIBRARIES install-libLTLIBRARIES mostlyclean-compile \
distclean-compile clean-compile maintainer-clean-compile \
mostlyclean-libtool distclean-libtool clean-libtool \
maintainer-clean-libtool mostlyclean-binPROGRAMS distclean-binPROGRAMS \
clean-binPROGRAMS maintainer-clean-binPROGRAMS uninstall-binPROGRAMS \
install-binPROGRAMS uninstall-glibincludeHEADERS \
install-glibincludeHEADERS uninstall-glibsubincludeHEADERS \
install-glibsubincludeHEADERS install-data-recursive \
uninstall-data-recursive install-exec-recursive \
uninstall-exec-recursive installdirs-recursive uninstalldirs-recursive \
all-recursive check-recursive installcheck-recursive info-recursive \
dvi-recursive mostlyclean-recursive distclean-recursive clean-recursive \
maintainer-clean-recursive tags tags-recursive mostlyclean-tags \
distclean-tags clean-tags maintainer-clean-tags distdir info-am info \
dvi-am dvi check check-am installcheck-am installcheck install-exec-am \
install-exec install-data-local install-data-am install-data install-am \
install uninstall-local uninstall-am uninstall all-redirect all-am all \
installdirs-am installdirs mostlyclean-generic distclean-generic \
clean-generic maintainer-clean-generic clean mostlyclean distclean \
maintainer-clean


#install-ms-lib:
#	$(INSTALL) glib-2.0.lib $(DESTDIR)$(libdir)

#uninstall-ms-lib:
#	-rm $(DESTDIR)$(libdir)/glib-2.0.lib
install-ms-lib:
uninstall-ms-lib:

install-data-local: install-ms-lib install-libtool-import-lib
	@if test -f $(glibincludedir)/glist.h ; then					\
	  echo "*** Old headers found in $(glibincludedir). You should remove the" ;	\
	  echo "*** contents of this directory and type 'make install' again." ;	\
	  false ;									\
        fi

uninstall-local: uninstall-ms-lib uninstall-libtool-import-lib

#install-libtool-import-lib:
#	$(INSTALL) .libs/libglib-2.0.dll.a $(DESTDIR)$(libdir)
#uninstall-libtool-import-lib:
#	-rm $(DESTDIR)$(libdir)/libglib-2.0.dll.a
install-libtool-import-lib:
uninstall-libtool-import-lib:

# : glib.rc
#	$(top_srcdir)/build/win32/lt-compile-resource glib.rc 

glib-2.0.lib: libglib-2.0.la glib.def
	lib -name:libglib-2.0-0.dll -def:glib.def -out:$@

glib.rc: $(top_builddir)/config.status $(top_srcdir)/glib/glib.rc.in
	cd $(top_builddir) && CONFIG_FILES=glib/$@ CONFIG_HEADERS= $(SHELL) ./config.status

makefile.mingw: $(top_builddir)/config.status $(top_srcdir)/glib/makefile.mingw.in
	cd $(top_builddir) && CONFIG_FILES=glib/$@ CONFIG_HEADERS= $(SHELL) ./config.status

makefile.msc: $(top_builddir)/config.status $(top_srcdir)/glib/makefile.msc.in
	cd $(top_builddir) && CONFIG_FILES=glib/$@ CONFIG_HEADERS= $(SHELL) ./config.status

dist-hook: $(BUILT_EXTRA_DIST)
	files='$(BUILT_EXTRA_DIST)'; \
	for f in $$files; do \
	  if test -f $$f; then d=.; else d=$(srcdir); fi; \
	  cp $$d/$$f $(distdir) || exit 1; done

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
