# Makefile.in generated automatically by automake 1.4-p6 from Makefile.am

# Copyright (C) 1994, 1995-8, 1999, 2001 Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.


SHELL = /bin/sh

srcdir = .
top_srcdir = ..

prefix = /usr/local
exec_prefix = ${prefix}

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include

DESTDIR =

pkgdatadir = $(datadir)/glib
pkglibdir = $(libdir)/glib
pkgincludedir = $(includedir)/glib

top_builddir = ..

ACLOCAL = /home/general/cn_proc/glib-2.0.7/missing aclocal-1.4
AUTOCONF = /home/general/cn_proc/glib-2.0.7/missing autoconf
AUTOMAKE = /home/general/cn_proc/glib-2.0.7/missing automake-1.4
AUTOHEADER = /home/general/cn_proc/glib-2.0.7/missing autoheader

INSTALL = /usr/bin/install -c
INSTALL_PROGRAM = ${INSTALL} $(AM_INSTALL_PROGRAM_FLAGS)
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL}
transform = s,x,x,

NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
host_alias = 
host_triplet = x86_64-unknown-linux-gnu
AS = @AS@
AWK = gawk
CATALOGS =  ar.gmo az.gmo be.gmo bg.gmo ca.gmo cs.gmo de.gmo el.gmo es.gmo eu.gmo fr.gmo gl.gmo ja.gmo ko.gmo ms.gmo nl.gmo nn.gmo no.gmo pl.gmo pt.gmo pt_BR.gmo ro.gmo ru.gmo sk.gmo sl.gmo sv.gmo ta.gmo tr.gmo uk.gmo vi.gmo zh_CN.gmo zh_TW.gmo
CATOBJEXT = .gmo
CC = gcc
CXX = 
DATADIRNAME = share
DB2HTML = false
DISABLE_MEM_POOLS = 
DLLTOOL = @DLLTOOL@
ECHO = echo
ENABLE_GC_FRIENDLY = 
EXEEXT = 
GETTEXT_PACKAGE = glib20
GIO = giounix.lo
GLIBC21 = yes
GLIB_BINARY_AGE = 7
GLIB_DEBUG_FLAGS = 
GLIB_DEF = 
GLIB_GENMARSHAL = 
GLIB_INTERFACE_AGE = 7
GLIB_MAJOR_VERSION = 2
GLIB_MICRO_VERSION = 7
GLIB_MINOR_VERSION = 0
GLIB_VERSION = 2.0.7
GMODULE_DEF = 
GMOFILES =  ar.gmo az.gmo be.gmo bg.gmo ca.gmo cs.gmo de.gmo el.gmo es.gmo eu.gmo fr.gmo gl.gmo ja.gmo ko.gmo ms.gmo nl.gmo nn.gmo no.gmo pl.gmo pt.gmo pt_BR.gmo ro.gmo ru.gmo sk.gmo sl.gmo sv.gmo ta.gmo tr.gmo uk.gmo vi.gmo zh_CN.gmo zh_TW.gmo
GMSGFMT = /usr/bin/msgfmt
GOBJECT_DEF = 
GSPAWN = gspawn.lo
GTHREAD_COMPILE_IMPL_DEFINES = -D_POSIX4_DRAFT_SOURCE -D_POSIX4A_DRAFT10_SOURCE -U_OSF_SOURCE
GTHREAD_DEF = 
GTKDOC = false
G_LIBS_EXTRA = 
G_LIB_WIN32_RESOURCE = 
G_MODULE_BROKEN_RTLD_GLOBAL = 0
G_MODULE_HAVE_DLERROR = 1
G_MODULE_IMPL = G_MODULE_IMPL_DL
G_MODULE_LDFLAGS = -Wl,--export-dynamic
G_MODULE_LIBS = -ldl
G_MODULE_LIBS_EXTRA = 
G_MODULE_NEED_USCORE = 0
G_MODULE_PLUGIN_LIBS = 
G_MODULE_SUPPORTED = true
G_MODULE_WIN32_RESOURCE = 
G_OBJECT_WIN32_RESOURCE = 
G_THREAD_CFLAGS = -D_REENTRANT
G_THREAD_LIBS = -lpthread 
G_THREAD_LIBS_EXTRA = 
G_THREAD_WIN32_RESOURCE = 
HAVE_GTK_DOC = 
HTML_DIR = ${datadir}/gtk-doc/html
ICONV_LIBS = 
INDENT = 
INSTOBJEXT = .mo
INTLDEPS = 
INTLLIBS = 
INTLOBJS = 
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LN_S = ln -s
LT_AGE = 0
LT_CURRENT = 0
LT_CURRENT_MINUS_AGE = 0
LT_RELEASE = 2.0
LT_REVISION = 7
MAINT = #
MAKEINFO = /home/general/cn_proc/glib-2.0.7/missing makeinfo
MKINSTALLDIRS = ./mkinstalldirs
OBJDUMP = @OBJDUMP@
OBJEXT = o
PACKAGE = glib
PERL = perl
PERL_PATH = /usr/bin/perl
PKG_CONFIG = /usr/bin/pkg-config
PLATFORMDEP = 
POFILES =  ar.po az.po be.po bg.po ca.po cs.po de.po el.po es.po eu.po fr.po gl.po ja.po ko.po ms.po nl.po nn.po no.po pl.po pt.po pt_BR.po ro.po ru.po sk.po sl.po sv.po ta.po tr.po uk.po vi.po zh_CN.po zh_TW.po
POSUB = po
RANLIB = ranlib
REBUILD = 
STRIP = strip
STRIP_BEGIN = $(strip $(STRIP_DUMMY)
STRIP_DUMMY = 
STRIP_END = )
TESTGMODULE_EXP = 
USE_NLS = yes
VERSION = 2.0.7
ms_librarian = 

INCLUDES = -I$(top_srcdir) -I$(top_srcdir)/glib -I$(top_srcdir)/gthread \
	-DG_LOG_DOMAIN=\"GThread\" -D_POSIX4_DRAFT_SOURCE -D_POSIX4A_DRAFT10_SOURCE -U_OSF_SOURCE \
	


EXTRA_DIST = \
		makefile.mingw.in	\
		makefile.msc.in		\
		gthread-posix.c		\
		gthread-solaris.c	\
		gthread-win32.c		\
		gthread-none.c		\
		gthread.def		\
		gthread.rc.in


BUILT_EXTRA_DIST = \
		makefile.mingw		\
		makefile.msc		\
		gthread.rc


libglib = $(top_builddir)/glib/libglib-2.0.la

top_builddir_full = `cd \$(top_builddir); pwd`

lib_LTLIBRARIES = libgthread-2.0.la

#noinst_DATA = #gthread-2.0.lib

#no_undefined = #-no-undefined

#export_symbols = #-export-symbols gthread.def

libgthread_2_0_la_SOURCES = gthread-impl.c
libgthread_2_0_la_LDFLAGS = \
	-version-info $(LT_CURRENT):$(LT_REVISION):$(LT_AGE) \
	-export-dynamic $(no_undefined) $(export_symbols)


libgthread_2_0_la_LIBADD =   -lpthread  $(libglib)

libgthread_2_0_la_DEPENDENCIES =  
mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_HEADER = ../config.h
CONFIG_CLEAN_FILES = 
LTLIBRARIES =  $(lib_LTLIBRARIES)


DEFS = -DHAVE_CONFIG_H -I. -I$(srcdir) -I..
CPPFLAGS = 
LDFLAGS = 
LIBS =  
libgthread_2_0_la_OBJECTS =  gthread-impl.lo
CFLAGS = -g -O2 -Wall -D_REENTRANT
COMPILE = $(CC) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) --mode=compile $(CC) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(LIBTOOL) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(LDFLAGS) -o $@
DATA =  $(noinst_DATA)

DIST_COMMON =  ChangeLog Makefile.am Makefile.in


DISTFILES = $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST)

TAR = gtar
GZIP_ENV = --best
SOURCES = $(libgthread_2_0_la_SOURCES)
OBJECTS = $(libgthread_2_0_la_OBJECTS)

all: all-redirect
.SUFFIXES:
.SUFFIXES: .S .c .lo .o .obj .s
$(srcdir)/Makefile.in: # Makefile.am $(top_srcdir)/configure.in $(ACLOCAL_M4) 
	cd $(top_srcdir) && $(AUTOMAKE) --gnu --include-deps gthread/Makefile

Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status
	cd $(top_builddir) \
	  && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status


mostlyclean-libLTLIBRARIES:

clean-libLTLIBRARIES:
	-test -z "$(lib_LTLIBRARIES)" || rm -f $(lib_LTLIBRARIES)

distclean-libLTLIBRARIES:

maintainer-clean-libLTLIBRARIES:

install-libLTLIBRARIES: $(lib_LTLIBRARIES)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(libdir)
	@list='$(lib_LTLIBRARIES)'; for p in $$list; do \
	  if test -f $$p; then \
	    echo "$(LIBTOOL)  --mode=install $(INSTALL) $$p $(DESTDIR)$(libdir)/$$p"; \
	    $(LIBTOOL)  --mode=install $(INSTALL) $$p $(DESTDIR)$(libdir)/$$p; \
	  else :; fi; \
	done

uninstall-libLTLIBRARIES:
	@$(NORMAL_UNINSTALL)
	list='$(lib_LTLIBRARIES)'; for p in $$list; do \
	  $(LIBTOOL)  --mode=uninstall rm -f $(DESTDIR)$(libdir)/$$p; \
	done

.c.o:
	$(COMPILE) -c $<

# FIXME: We should only use cygpath when building on Windows,
# and only if it is available.
.c.obj:
	$(COMPILE) -c `cygpath -w $<`

.s.o:
	$(COMPILE) -c $<

.S.o:
	$(COMPILE) -c $<

mostlyclean-compile:
	-rm -f *.o core *.core
	-rm -f *.$(OBJEXT)

clean-compile:

distclean-compile:
	-rm -f *.tab.c

maintainer-clean-compile:

.c.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

.s.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

.S.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:

maintainer-clean-libtool:

libgthread-2.0.la: $(libgthread_2_0_la_OBJECTS) $(libgthread_2_0_la_DEPENDENCIES)
	$(LINK) -rpath $(libdir) $(libgthread_2_0_la_LDFLAGS) $(libgthread_2_0_la_OBJECTS) $(libgthread_2_0_la_LIBADD) $(LIBS)

tags: TAGS

ID: $(HEADERS) $(SOURCES) $(LISP)
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	here=`pwd` && cd $(srcdir) \
	  && mkid -f$$here/ID $$unique $(LISP)

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(ETAGS_ARGS)$$unique$(LISP)$$tags" \
	  || (cd $(srcdir) && etags $(ETAGS_ARGS) $$tags  $$unique $(LISP) -o $$here/TAGS)

mostlyclean-tags:

clean-tags:

distclean-tags:
	-rm -f TAGS ID

maintainer-clean-tags:

distdir = $(top_builddir)/$(PACKAGE)-$(VERSION)/$(subdir)

subdir = gthread

distdir: $(DISTFILES)
	@for file in $(DISTFILES); do \
	  d=$(srcdir); \
	  if test -d $$d/$$file; then \
	    cp -pr $$d/$$file $(distdir)/$$file; \
	  else \
	    test -f $(distdir)/$$file \
	    || ln $$d/$$file $(distdir)/$$file 2> /dev/null \
	    || cp -p $$d/$$file $(distdir)/$$file || :; \
	  fi; \
	done
	$(MAKE) $(AM_MAKEFLAGS) top_distdir="$(top_distdir)" distdir="$(distdir)" dist-hook
gthread-impl.lo gthread-impl.o : gthread-impl.c ../config.h \
	../glib/glib.h ../glib/galloca.h ../glib/gtypes.h \
	../glibconfig.h ../glib/gmacros.h ../glib/garray.h \
	../glib/gasyncqueue.h ../glib/gthread.h ../glib/gerror.h \
	../glib/gquark.h ../glib/gbacktrace.h ../glib/gcache.h \
	../glib/glist.h ../glib/gmem.h ../glib/gcompletion.h \
	../glib/gconvert.h ../glib/gdataset.h ../glib/gdate.h \
	../glib/gdir.h ../glib/gfileutils.h ../glib/ghash.h \
	../glib/ghook.h ../glib/giochannel.h ../glib/gmain.h \
	../glib/gslist.h ../glib/gstring.h ../glib/gunicode.h \
	../glib/gmarkup.h ../glib/gmessages.h ../glib/gnode.h \
	../glib/gpattern.h ../glib/gprimes.h ../glib/gqsort.h \
	../glib/gqueue.h ../glib/grand.h ../glib/grel.h \
	../glib/gscanner.h ../glib/gshell.h ../glib/gspawn.h \
	../glib/gstrfuncs.h ../glib/gthreadpool.h ../glib/gtimer.h \
	../glib/gtree.h ../glib/gutils.h gthread-posix.c

info-am:
info: info-am
dvi-am:
dvi: dvi-am
check-am: all-am
check: check-am
installcheck-am:
installcheck: installcheck-am
install-exec-am: install-libLTLIBRARIES
install-exec: install-exec-am

install-data-am: install-data-local
install-data: install-data-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am
install: install-am
uninstall-am: uninstall-libLTLIBRARIES uninstall-local
uninstall: uninstall-am
all-am: Makefile $(LTLIBRARIES) $(DATA)
all-redirect: all-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) AM_INSTALL_PROGRAM_FLAGS=-s install
installdirs:
	$(mkinstalldirs)  $(DESTDIR)$(libdir)


mostlyclean-generic:

clean-generic:

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES)
	-rm -f config.cache config.log stamp-h stamp-h[0-9]*

maintainer-clean-generic:
mostlyclean-am:  mostlyclean-libLTLIBRARIES mostlyclean-compile \
		mostlyclean-libtool mostlyclean-tags \
		mostlyclean-generic

mostlyclean: mostlyclean-am

clean-am:  clean-libLTLIBRARIES clean-compile clean-libtool clean-tags \
		clean-generic mostlyclean-am

clean: clean-am

distclean-am:  distclean-libLTLIBRARIES distclean-compile \
		distclean-libtool distclean-tags distclean-generic \
		clean-am
	-rm -f libtool

distclean: distclean-am

maintainer-clean-am:  maintainer-clean-libLTLIBRARIES \
		maintainer-clean-compile maintainer-clean-libtool \
		maintainer-clean-tags maintainer-clean-generic \
		distclean-am
	@echo "This command is intended for maintainers to use;"
	@echo "it deletes files that may require special tools to rebuild."

maintainer-clean: maintainer-clean-am

.PHONY: mostlyclean-libLTLIBRARIES distclean-libLTLIBRARIES \
clean-libLTLIBRARIES maintainer-clean-libLTLIBRARIES \
uninstall-libLTLIBRARIES install-libLTLIBRARIES mostlyclean-compile \
distclean-compile clean-compile maintainer-clean-compile \
mostlyclean-libtool distclean-libtool clean-libtool \
maintainer-clean-libtool tags mostlyclean-tags distclean-tags \
clean-tags maintainer-clean-tags distdir info-am info dvi-am dvi check \
check-am installcheck-am installcheck install-exec-am install-exec \
install-data-local install-data-am install-data install-am install \
uninstall-local uninstall-am uninstall all-redirect all-am all \
installdirs mostlyclean-generic distclean-generic clean-generic \
maintainer-clean-generic clean mostlyclean distclean maintainer-clean


#install-ms-lib:
#	$(INSTALL) gthread-2.0.lib $(DESTDIR)$(libdir)

#uninstall-ms-lib:
#	-rm $(DESTDIR)$(libdir)/gthread-2.0.lib
install-ms-lib:
uninstall-ms-lib:

#install-libtool-import-lib:
#	$(INSTALL) .libs/libgthread-2.0.dll.a $(DESTDIR)$(libdir)
#uninstall-libtool-import-lib:
#	-rm $(DESTDIR)$(libdir)/libgthread-2.0.dll.a
install-libtool-import-lib:
uninstall-libtool-import-lib:

# : gthread.rc
#	$(top_srcdir)/build/win32/lt-compile-resource gthread.rc 

gthread-2.0.lib: libgthread-2.0.la gthread.def
	lib -name:libgthread-2.0-0.dll -def:gthread.def -out:$@

gthread.rc: $(top_builddir)/config.status $(top_srcdir)/gthread/gthread.rc.in
	cd $(top_builddir) && CONFIG_FILES=gthread/$@ CONFIG_HEADERS= $(SHELL) ./config.status

makefile.mingw: $(top_builddir)/config.status $(top_srcdir)/gthread/makefile.mingw.in
	cd $(top_builddir) && CONFIG_FILES=gthread/$@ CONFIG_HEADERS= $(SHELL) ./config.status

makefile.msc: $(top_builddir)/config.status $(top_srcdir)/gthread/makefile.msc.in
	cd $(top_builddir) && CONFIG_FILES=gthread/$@ CONFIG_HEADERS= $(SHELL) ./config.status

dist-hook: $(BUILT_EXTRA_DIST)
	files='$(BUILT_EXTRA_DIST)'; \
	for f in $$files; do \
	  if test -f $$f; then d=.; else d=$(srcdir); fi; \
	  cp $$d/$$f $(distdir) || exit 1; done

install-data-local: install-ms-lib install-libtool-import-lib

uninstall-local: uninstall-ms-lib uninstall-libtool-import-lib

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
